"""
デモモード用の合成トレンド語彙。

APIキーが無い状態でも UI の全機能を試せるようにするためのデータ。
実データに切り替えた瞬間から使われなくなるので、好きなだけ遊んでよい。

各エントリ:
    name   表示名
    cat    カテゴリID（classify.py と同じ体系）
    base   出やすさの重み
    slot   出やすい時間帯（morning/daytime/evening/night/latenight）
    daily  日替わりでバズるフラグ
    weekly 週末に強いフラグ
    count  "none" で tweet_count 欠損を再現（X API でもよくある）
"""

from __future__ import annotations

from functools import lru_cache

from .locations import BY_WOEID

JA_COUNTRIES = {"JP"}


def locale_for(woeid: int) -> str:
    loc = BY_WOEID.get(woeid)
    if loc and loc.country in JA_COUNTRIES:
        return "ja"
    if woeid == 1:
        return "global"
    return "en"


def time_slot(jst_hour: int) -> str:
    if 5 <= jst_hour < 9:
        return "morning"
    if 9 <= jst_hour < 15:
        return "daytime"
    if 15 <= jst_hour < 19:
        return "evening"
    if 19 <= jst_hour < 24:
        return "night"
    return "latenight"


def _t(name, cat, base=100, slot=None, daily=False, weekly=False, count="normal"):
    return {"name": name, "cat": cat, "base": base, "slot": slot,
            "daily": daily, "weekly": weekly, "count": count}


# --------------------------------------------------------------------------- #
# 日本語プール
# --------------------------------------------------------------------------- #

_JA: list[dict] = [
    # --- エンタメ ---
    _t("#乃木坂46", "entertainment", 150, "night"),
    _t("Snow Man", "entertainment", 170, "night"),
    _t("なにわ男子", "entertainment", 130, "night"),
    _t("timelesz", "entertainment", 110, "night"),
    _t("Number_i", "entertainment", 120, "evening"),
    _t("Mrs. GREEN APPLE", "entertainment", 140, "daytime"),
    _t("YOASOBI", "entertainment", 130, "evening"),
    _t("米津玄師", "entertainment", 125, "evening"),
    _t("Ado", "entertainment", 120, "night"),
    _t("Vaundy", "entertainment", 95, "night"),
    _t("Official髭男dism", "entertainment", 110, "daytime"),
    _t("back number", "entertainment", 85, "night"),
    _t("King Gnu", "entertainment", 100, "night"),
    _t("緑黄色社会", "entertainment", 80, "daytime"),
    _t("imase", "entertainment", 75, "evening"),
    _t("優里", "entertainment", 70, "night"),
    _t("新しい学校のリーダーズ", "entertainment", 85, "evening", daily=True),
    _t("橋本環奈", "entertainment", 105, "evening", daily=True),
    _t("広瀬すず", "entertainment", 95, "daytime", daily=True),
    _t("浜辺美波", "entertainment", 90, "evening", daily=True),
    _t("横浜流星", "entertainment", 88, "night", daily=True),
    _t("菅田将暉", "entertainment", 92, "night", daily=True),
    _t("山﨑賢人", "entertainment", 86, "evening", daily=True),
    _t("吉沢亮", "entertainment", 80, "daytime", daily=True),
    _t("永野芽郁", "entertainment", 78, "daytime", daily=True),
    _t("森七菜", "entertainment", 70, "evening", daily=True),
    _t("有吉弘行", "entertainment", 95, "night"),
    _t("ダウンタウン", "entertainment", 100, "night", daily=True),
    _t("マツコ・デラックス", "entertainment", 88, "night"),
    _t("ナインティナイン", "entertainment", 82, "night"),
    _t("かまいたち", "entertainment", 90, "evening"),
    _t("チョコレートプラネット", "entertainment", 76, "evening"),
    _t("さらば青春の光", "entertainment", 68, "latenight"),
    _t("M-1グランプリ", "entertainment", 140, "night", weekly=True),
    _t("キングオブコント", "entertainment", 120, "night", weekly=True),
    _t("紅白歌合戦", "entertainment", 160, "night"),
    _t("ミュージックステーション", "entertainment", 110, "night"),
    _t("24時間テレビ", "entertainment", 130, "night", weekly=True),
    _t("ガキの使い", "entertainment", 95, "latenight", weekly=True),
    _t("笑点", "entertainment", 90, "evening", weekly=True),
    _t("大河ドラマ", "entertainment", 105, "night", weekly=True),
    _t("朝ドラ", "entertainment", 115, "morning"),
    _t("ブラタモリ", "entertainment", 70, "evening", weekly=True),
    _t("月曜から夜ふかし", "entertainment", 92, "latenight", weekly=True),
    _t("アメトーーク", "entertainment", 88, "latenight", weekly=True),
    _t("相席食堂", "entertainment", 74, "latenight", weekly=True),
    _t("芸能界", "entertainment", 65, "daytime", daily=True),
    _t("文春", "news", 130, "evening", daily=True),
    _t("会見", "entertainment", 110, "daytime", daily=True),
    _t("結婚", "entertainment", 120, "evening", daily=True),
    _t("熱愛報道", "entertainment", 105, "evening", daily=True),
    _t("活動休止", "entertainment", 95, "evening", daily=True),
    _t("卒業", "entertainment", 88, "evening", daily=True),
    _t("炎上", "news", 125, "night", daily=True),

    # --- K-POP / グローバル ---
    _t("BTS", "entertainment", 150, "evening"),
    _t("JUNG KOOK", "entertainment", 110, "evening", daily=True),
    _t("BLACKPINK", "entertainment", 130, "evening"),
    _t("NewJeans", "entertainment", 115, "evening", daily=True),
    _t("LE SSERAFIM", "entertainment", 105, "evening", daily=True),
    _t("IVE", "entertainment", 100, "evening", daily=True),
    _t("aespa", "entertainment", 95, "evening", daily=True),
    _t("Stray Kids", "entertainment", 108, "night", daily=True),
    _t("SEVENTEEN", "entertainment", 112, "night", daily=True),
    _t("ENHYPEN", "entertainment", 96, "night", daily=True),
    _t("TWICE", "entertainment", 102, "evening"),
    _t("NiziU", "entertainment", 98, "evening"),
    _t("K-POP", "entertainment", 80, "night"),
    _t("MAMA", "entertainment", 120, "night", weekly=True),
    _t("Taylor Swift", "entertainment", 118, "night", daily=True),
    _t("Billie Eilish", "entertainment", 82, "night", daily=True),
    _t("Sabrina Carpenter", "entertainment", 86, "evening", daily=True),
    _t("Billboard", "entertainment", 78, "daytime"),

    # --- アニメ / ゲーム ---
    _t("鬼滅の刃", "anime_game", 175, "night"),
    _t("無限城編", "anime_game", 150, "night"),
    _t("呪術廻戦", "anime_game", 140, "latenight"),
    _t("ONE PIECE", "anime_game", 160, "morning", weekly=True),
    _t("ワンピース", "anime_game", 155, "night"),
    _t("チェンソーマン", "anime_game", 125, "latenight", daily=True),
    _t("SPY×FAMILY", "anime_game", 118, "night", weekly=True),
    _t("葬送のフリーレン", "anime_game", 112, "night", weekly=True),
    _t("推しの子", "anime_game", 108, "night", daily=True),
    _t("ブルーロック", "anime_game", 104, "night", daily=True),
    _t("ダンダダン", "anime_game", 116, "latenight", daily=True),
    _t("薬屋のひとりごと", "anime_game", 100, "night", weekly=True),
    _t("僕のヒーローアカデミア", "anime_game", 95, "daytime"),
    _t("進撃の巨人", "anime_game", 90, "latenight"),
    _t("ガンダム", "anime_game", 98, "evening", daily=True),
    _t("ジブリ", "anime_game", 120, "night", weekly=True),
    _t("宮崎駿", "anime_game", 88, "night", daily=True),
    _t("新海誠", "anime_game", 84, "evening", daily=True),
    _t("ポケモン", "anime_game", 145, "evening"),
    _t("ピカチュウ", "anime_game", 92, "evening", daily=True),
    _t("プリキュア", "anime_game", 110, "morning", weekly=True),
    _t("ドラゴンボール", "anime_game", 105, "morning", weekly=True),
    _t("劇場版", "anime_game", 96, "daytime", daily=True),
    _t("アニメ", "anime_game", 88, "night"),
    _t("声優", "anime_game", 92, "evening", daily=True),
    _t("VTuber", "anime_game", 118, "latenight"),
    _t("にじさんじ", "anime_game", 112, "latenight", daily=True),
    _t("ホロライブ", "anime_game", 114, "latenight", daily=True),
    _t("初音ミク", "anime_game", 90, "evening"),
    _t("コミケ", "anime_game", 140, "morning", weekly=True),
    _t("原神", "anime_game", 150, "night"),
    _t("崩壊：スターレイル", "anime_game", 122, "night", daily=True),
    _t("ゼンレスゾーンゼロ", "anime_game", 108, "night", daily=True),
    _t("鳴潮", "anime_game", 94, "night", daily=True),
    _t("モンハン", "anime_game", 145, "night", daily=True),
    _t("モンスターハンターワイルズ", "anime_game", 130, "night"),
    _t("スマブラ", "anime_game", 105, "night"),
    _t("スプラトゥーン", "anime_game", 102, "evening"),
    _t("マリオカート", "anime_game", 96, "evening"),
    _t("ゼルダの伝説", "anime_game", 98, "night", daily=True),
    _t("FORTNITE", "anime_game", 104, "night"),
    _t("Apex Legends", "anime_game", 99, "latenight"),
    _t("VALORANT", "anime_game", 106, "latenight"),
    _t("ウマ娘", "anime_game", 110, "evening"),
    _t("FGO", "anime_game", 128, "night", daily=True),
    _t("ブルアカ", "anime_game", 92, "latenight", daily=True),
    _t("プロセカ", "anime_game", 100, "night", daily=True),
    _t("Nintendo Switch 2", "anime_game", 126, "daytime", daily=True),
    _t("PlayStation", "tech", 88, "evening", daily=True),
    _t("Steam", "anime_game", 90, "latenight"),
    _t("Nintendo Direct", "anime_game", 140, "night", daily=True),
    _t("State of Play", "anime_game", 130, "night", daily=True),
    _t("ゲーム", "anime_game", 70, "night"),

    # --- スポーツ ---
    _t("大谷翔平", "sports", 210, "morning", daily=True),
    _t("ドジャース", "sports", 180, "morning", daily=True),
    _t("山本由伸", "sports", 140, "morning", daily=True),
    _t("佐々木朗希", "sports", 135, "morning", daily=True),
    _t("MLB", "sports", 120, "morning"),
    _t("ホームラン", "sports", 110, "morning", daily=True),
    _t("日本シリーズ", "sports", 170, "night", weekly=True),
    _t("プロ野球", "sports", 160, "night"),
    _t("阪神", "sports", 140, "night", daily=True),
    _t("巨人", "sports", 135, "night", daily=True),
    _t("ソフトバンク", "sports", 115, "night", daily=True),
    _t("広島", "sports", 100, "night", daily=True),
    _t("ドラフト会議", "sports", 150, "evening", weekly=True),
    _t("甲子園", "sports", 175, "daytime", weekly=True),
    _t("侍ジャパン", "sports", 130, "night", weekly=True),
    _t("サッカー日本代表", "sports", 165, "night", daily=True),
    _t("森保ジャパン", "sports", 120, "night", daily=True),
    _t("三笘薫", "sports", 128, "night", daily=True),
    _t("久保建英", "sports", 122, "night", daily=True),
    _t("南野拓実", "sports", 96, "night", daily=True),
    _t("上田綺世", "sports", 92, "night", daily=True),
    _t("Jリーグ", "sports", 118, "evening", weekly=True),
    _t("浦和レッズ", "sports", 95, "evening", weekly=True),
    _t("鹿島アントラーズ", "sports", 88, "evening", weekly=True),
    _t("ヴィッセル神戸", "sports", 86, "evening", weekly=True),
    _t("プレミアリーグ", "sports", 132, "night", weekly=True),
    _t("レアル・マドリード", "sports", 126, "night", daily=True),
    _t("バルセロナ", "sports", 120, "night", daily=True),
    _t("アーセナル", "sports", 104, "night", weekly=True),
    _t("リバプール", "sports", 108, "night", weekly=True),
    _t("マンチェスター・シティ", "sports", 102, "night", weekly=True),
    _t("チャンピオンズリーグ", "sports", 150, "latenight", weekly=True),
    _t("W杯", "sports", 190, "night", daily=True),
    _t("ワールドカップ", "sports", 185, "night", daily=True),
    _t("八村塁", "sports", 100, "morning", daily=True),
    _t("NBA", "sports", 115, "morning"),
    _t("Bリーグ", "sports", 82, "evening", weekly=True),
    _t("大相撲", "sports", 140, "daytime", weekly=True),
    _t("横綱", "sports", 105, "daytime", weekly=True),
    _t("井上尚弥", "sports", 145, "night", weekly=True),
    _t("ボクシング", "sports", 95, "night", weekly=True),
    _t("錦織圭", "sports", 88, "evening", daily=True),
    _t("大坂なおみ", "sports", 102, "evening", daily=True),
    _t("全豪オープン", "sports", 120, "morning", weekly=True),
    _t("ウィンブルドン", "sports", 118, "night", weekly=True),
    _t("松山英樹", "sports", 90, "morning", daily=True),
    _t("マスターズ", "sports", 116, "night", weekly=True),
    _t("F1", "sports", 124, "night", weekly=True),
    _t("角田裕毅", "sports", 108, "night", weekly=True),
    _t("フェルスタッペン", "sports", 96, "night", weekly=True),
    _t("羽生結弦", "sports", 130, "evening", daily=True),
    _t("フィギュアスケート", "sports", 106, "night", weekly=True),
    _t("箱根駅伝", "sports", 160, "morning", weekly=True),
    _t("マラソン", "sports", 110, "morning", weekly=True),
    _t("バレーボール", "sports", 92, "evening", weekly=True),
    _t("石川祐希", "sports", 86, "evening", daily=True),
    _t("卓球", "sports", 84, "night", weekly=True),
    _t("張本智和", "sports", 90, "night", daily=True),
    _t("オリンピック", "sports", 140, "daytime"),

    # --- テック ---
    _t("ChatGPT", "tech", 160, "daytime"),
    _t("OpenAI", "tech", 170, "daytime", daily=True),
    _t("Grok", "tech", 125, "night", daily=True),
    _t("Gemini", "tech", 118, "daytime", daily=True),
    _t("Claude", "tech", 104, "daytime", daily=True),
    _t("生成AI", "tech", 132, "daytime"),
    _t("AI", "tech", 150, "daytime"),
    _t("イーロン・マスク", "tech", 145, "night", daily=True),
    _t("Tesla", "tech", 110, "night", daily=True),
    _t("iPhone", "tech", 165, "evening", daily=True),
    _t("Apple", "tech", 150, "evening", daily=True),
    _t("新型MacBook", "tech", 98, "night", daily=True),
    _t("Nintendo", "tech", 92, "daytime"),
    _t("ソニー", "tech", 96, "daytime", daily=True),
    _t("NVIDIA", "tech", 108, "morning", daily=True),
    _t("Google", "tech", 102, "daytime"),
    _t("Microsoft", "tech", 94, "daytime"),
    _t("Amazon", "tech", 100, "evening"),
    _t("サイバー攻撃", "news", 112, "daytime", daily=True),
    _t("情報漏えい", "news", 106, "daytime", daily=True),
    _t("通信障害", "tech", 140, "daytime", daily=True),
    _t("アップデート", "tech", 86, "daytime"),
    _t("障害発生", "tech", 120, "daytime", daily=True),
    _t("GitHub", "tech", 78, "latenight"),
    _t("Python", "tech", 80, "latenight"),
    _t("スタートアップ", "tech", 76, "daytime"),
    _t("量子コンピュータ", "tech", 88, "daytime", daily=True),
    _t("自動運転", "tech", 94, "daytime", daily=True),
    _t("ロボット", "tech", 82, "daytime"),
    _t("ドローン", "tech", 74, "daytime", daily=True),
    _t("スペースX", "tech", 104, "night", daily=True),

    # --- 経済 ---
    _t("日経平均", "finance", 165, "morning"),
    _t("株価", "finance", 140, "morning"),
    _t("円安", "finance", 155, "daytime"),
    _t("ドル円", "finance", 120, "daytime"),
    _t("為替", "finance", 108, "morning"),
    _t("暴落", "finance", 145, "morning", daily=True),
    _t("急騰", "finance", 118, "morning", daily=True),
    _t("日銀", "finance", 130, "daytime", daily=True),
    _t("植田総裁", "finance", 112, "daytime", daily=True),
    _t("利上げ", "finance", 126, "daytime", daily=True),
    _t("金利", "finance", 104, "daytime"),
    _t("インフレ", "finance", 98, "daytime"),
    _t("FRB", "finance", 106, "morning"),
    _t("パウエル議長", "finance", 96, "morning", daily=True),
    _t("ビットコイン", "finance", 148, "night", daily=True),
    _t("仮想通貨", "finance", 118, "night"),
    _t("イーサリアム", "finance", 92, "night", daily=True),
    _t("XRP", "finance", 88, "night", daily=True),
    _t("NISA", "finance", 116, "daytime"),
    _t("新NISA", "finance", 124, "daytime"),
    _t("投資信託", "finance", 84, "daytime"),
    _t("物価高", "finance", 132, "daytime"),
    _t("ガソリン価格", "finance", 96, "morning"),
    _t("電気代", "finance", 90, "daytime"),
    _t("賃上げ", "finance", 108, "daytime", daily=True),
    _t("春闘", "finance", 100, "daytime"),
    _t("ボーナス", "finance", 122, "daytime", weekly=True),
    _t("決算", "finance", 110, "evening", daily=True),
    _t("関税", "finance", 118, "morning", daily=True),
    _t("トランプ関税", "finance", 128, "morning", daily=True),
    _t("トヨタ", "finance", 94, "daytime", daily=True),
    _t("任天堂", "finance", 112, "daytime", daily=True),
    _t("ソフトバンクグループ", "finance", 98, "daytime", daily=True),
    _t("上場", "finance", 86, "daytime", daily=True),
    _t("IPO", "finance", 80, "daytime", daily=True),

    # --- ニュース / 政治 / 災害 ---
    _t("地震", "news", 220, None, daily=True),
    _t("震度", "news", 190, None, daily=True),
    _t("津波注意報", "news", 160, None, daily=True),
    _t("台風", "news", 200, "daytime", daily=True),
    _t("台風10号", "news", 170, "daytime", daily=True),
    _t("大雨警報", "news", 130, "morning", daily=True),
    _t("猛暑日", "news", 150, "daytime", daily=True),
    _t("熱中症", "news", 140, "daytime", daily=True),
    _t("大雪", "news", 135, "morning", daily=True),
    _t("火災", "news", 125, "night", daily=True),
    _t("事故", "news", 138, "daytime", daily=True),
    _t("事件", "news", 142, "evening", daily=True),
    _t("逮捕", "news", 156, "evening", daily=True),
    _t("送検", "news", 108, "daytime", daily=True),
    _t("裁判", "news", 114, "daytime", daily=True),
    _t("判決", "news", 120, "daytime", daily=True),
    _t("詐欺", "news", 102, "daytime", daily=True),
    _t("総理大臣", "news", 160, "daytime", daily=True),
    _t("首相", "news", 170, "daytime", daily=True),
    _t("内閣", "news", 128, "daytime"),
    _t("国会", "news", 134, "daytime"),
    _t("衆議院", "news", 122, "daytime"),
    _t("参議院", "news", 118, "daytime"),
    _t("解散", "news", 150, "daytime", daily=True),
    _t("選挙", "news", 185, "daytime", daily=True),
    _t("投票率", "news", 130, "evening", daily=True),
    _t("自民党", "news", 165, "daytime", daily=True),
    _t("総裁選", "news", 175, "daytime", daily=True),
    _t("立憲民主党", "news", 110, "daytime"),
    _t("日本維新の会", "news", 108, "daytime"),
    _t("国民民主党", "news", 104, "daytime"),
    _t("参政党", "news", 116, "daytime", daily=True),
    _t("れいわ新選組", "news", 96, "night"),
    _t("公明党", "news", 92, "daytime"),
    _t("日本共産党", "news", 88, "daytime"),
    _t("石破首相", "news", 150, "daytime", daily=True),
    _t("外交", "news", 96, "daytime"),
    _t("首脳会談", "news", 108, "daytime", daily=True),
    _t("ウクライナ", "news", 158, "daytime", daily=True),
    _t("ロシア", "news", 152, "daytime", daily=True),
    _t("停戦", "news", 130, "daytime", daily=True),
    _t("ガザ", "news", 144, "daytime", daily=True),
    _t("イスラエル", "news", 148, "daytime", daily=True),
    _t("イラン", "news", 120, "daytime", daily=True),
    _t("北朝鮮", "news", 126, "daytime", daily=True),
    _t("トランプ大統領", "news", 172, "night", daily=True),
    _t("米国", "news", 104, "daytime"),
    _t("中国", "news", 118, "daytime", daily=True),
    _t("韓国", "news", 112, "daytime", daily=True),
    _t("皇室", "news", 120, "daytime", daily=True),
    _t("天皇陛下", "news", 106, "daytime", weekly=True),
    _t("新型コロナウイルス", "news", 100, "daytime"),
    _t("インフルエンザ", "news", 132, "morning", daily=True),
    _t("ワクチン", "news", 98, "daytime"),
    _t("医療", "news", 86, "daytime"),
    _t("少子化", "news", 112, "daytime"),
    _t("人口減少", "news", 94, "daytime"),
    _t("移民", "news", 106, "night", daily=True),
    _t("年金", "news", 118, "daytime"),
    _t("社会保障", "news", 92, "daytime"),
    _t("防衛費", "news", 104, "daytime", daily=True),
    _t("原発", "news", 98, "daytime", daily=True),
    _t("電力", "news", 88, "daytime"),
    _t("山手線", "news", 140, "morning", daily=True),
    _t("運転見合わせ", "news", 155, "morning", daily=True),
    _t("遅延", "news", 138, "morning", daily=True),
    _t("新幹線", "news", 124, "morning", daily=True),
    _t("JR", "news", 110, "morning"),
    _t("高速道路", "news", 96, "daytime", daily=True),
    _t("渋滞", "news", 102, "evening", daily=True, weekly=True),
    _t("飛行機", "news", 90, "daytime", daily=True),
    _t("欠航", "news", 108, "morning", daily=True),

    # --- 暮らし / グルメ / 季節 ---
    _t("コンビニ", "lifestyle", 120, "daytime"),
    _t("セブンイレブン", "lifestyle", 108, "daytime", daily=True),
    _t("ファミマ", "lifestyle", 102, "daytime", daily=True),
    _t("ローソン", "lifestyle", 104, "daytime", daily=True),
    _t("新商品", "lifestyle", 116, "daytime", daily=True),
    _t("コラボ", "lifestyle", 118, "daytime", daily=True),
    _t("数量限定", "lifestyle", 96, "daytime"),
    _t("売り切れ", "lifestyle", 110, "daytime", daily=True),
    _t("スタバ", "lifestyle", 132, "morning", daily=True),
    _t("マクドナルド", "lifestyle", 128, "daytime", daily=True),
    _t("吉野家", "lifestyle", 92, "daytime"),
    _t("すき家", "lifestyle", 88, "daytime"),
    _t("ココス", "lifestyle", 80, "evening"),
    _t("サイゼリヤ", "lifestyle", 106, "evening"),
    _t("ケンタッキー", "lifestyle", 98, "evening", weekly=True),
    _t("ミスタードーナツ", "lifestyle", 84, "daytime"),
    _t("サーティワン", "lifestyle", 86, "evening", daily=True),
    _t("ユニクロ", "lifestyle", 130, "daytime", daily=True),
    _t("GU", "lifestyle", 100, "daytime", daily=True),
    _t("無印良品", "lifestyle", 94, "daytime"),
    _t("ニトリ", "lifestyle", 82, "daytime"),
    _t("コストコ", "lifestyle", 106, "daytime", weekly=True),
    _t("業務スーパー", "lifestyle", 90, "daytime"),
    _t("ドン・キホーテ", "lifestyle", 96, "night"),
    _t("ワークマン", "lifestyle", 88, "daytime"),
    _t("PayPay", "lifestyle", 124, "daytime", daily=True),
    _t("キャンペーン", "lifestyle", 112, "daytime", daily=True),
    _t("ポイント還元", "lifestyle", 92, "daytime"),
    _t("ブラックフライデー", "lifestyle", 140, "night"),
    _t("福袋", "lifestyle", 135, "morning"),
    _t("初売り", "lifestyle", 128, "morning"),
    _t("セール", "lifestyle", 104, "evening"),
    _t("ラーメン", "lifestyle", 118, "night"),
    _t("寿司", "lifestyle", 96, "evening"),
    _t("焼肉", "lifestyle", 92, "evening"),
    _t("カレー", "lifestyle", 88, "evening"),
    _t("スイーツ", "lifestyle", 100, "daytime"),
    _t("タピオカ", "lifestyle", 84, "evening"),
    _t("レシピ", "lifestyle", 90, "evening"),
    _t("節約", "lifestyle", 98, "daytime"),
    _t("ふるさと納税", "lifestyle", 114, "daytime"),
    _t("ディズニー", "lifestyle", 150, "daytime", weekly=True),
    _t("USJ", "lifestyle", 138, "daytime", weekly=True),
    _t("ユニバ", "lifestyle", 120, "daytime", weekly=True),
    _t("ジブリパーク", "lifestyle", 112, "daytime"),
    _t("旅行", "lifestyle", 108, "evening", weekly=True),
    _t("温泉", "lifestyle", 96, "evening", weekly=True),
    _t("ホテル", "lifestyle", 88, "evening"),
    _t("受験", "lifestyle", 132, "morning"),
    _t("大学入学共通テスト", "lifestyle", 150, "morning", weekly=True),
    _t("就活", "lifestyle", 126, "morning"),
    _t("転職", "lifestyle", 102, "daytime"),
    _t("リモートワーク", "lifestyle", 94, "morning"),
    _t("満員電車", "lifestyle", 88, "morning"),
    _t("育児", "lifestyle", 92, "morning"),
    _t("保育園", "lifestyle", 86, "morning"),
    _t("花粉症", "lifestyle", 138, "morning"),
    _t("桜", "lifestyle", 170, "daytime", weekly=True),
    _t("花見", "lifestyle", 140, "daytime", weekly=True),
    _t("紅葉", "lifestyle", 130, "daytime", weekly=True),
    _t("梅雨", "lifestyle", 118, "morning"),
    _t("初雪", "lifestyle", 128, "morning", daily=True),
    _t("気温", "lifestyle", 122, "morning"),
    _t("天気", "lifestyle", 116, "morning"),
    _t("クリスマス", "lifestyle", 180, "evening"),
    _t("ハロウィン", "lifestyle", 165, "evening"),
    _t("お正月", "lifestyle", 175, "morning"),
    _t("年末年始", "lifestyle", 145, "evening"),
    _t("ゴールデンウィーク", "lifestyle", 155, "morning"),
    _t("お盆", "lifestyle", 140, "morning"),
    _t("夏休み", "lifestyle", 150, "morning"),
    _t("冬休み", "lifestyle", 135, "morning"),
    _t("夏フェス", "lifestyle", 130, "daytime", weekly=True),
    _t("ROCK IN JAPAN", "lifestyle", 120, "daytime", weekly=True),
    _t("SUMMER SONIC", "lifestyle", 118, "daytime", weekly=True),
    _t("ライブ", "lifestyle", 126, "night", weekly=True),
    _t("コンサート", "lifestyle", 104, "night", weekly=True),
    _t("映画", "lifestyle", 132, "evening", weekly=True),
    _t("興行収入", "lifestyle", 98, "daytime", daily=True),
    _t("ネトフリ", "lifestyle", 106, "night", weekly=True),
    _t("Netflix", "lifestyle", 112, "night", weekly=True),
    _t("TVer", "lifestyle", 84, "night"),
    _t("ABEMA", "lifestyle", 86, "latenight"),
    _t("猫", "lifestyle", 145, "night", daily=True),
    _t("犬", "lifestyle", 110, "evening", daily=True),
    _t("#猫の日", "hashtag", 130, "daytime"),
    _t("#写真で一言", "hashtag", 96, "night"),
    _t("#今日の積み上げ", "hashtag", 88, "morning"),
    _t("#金曜ロードショー", "hashtag", 135, "night", weekly=True),
    _t("#日曜劇場", "hashtag", 140, "night", weekly=True),
    _t("#Mステ", "hashtag", 120, "night", weekly=True),
    _t("#紅白", "hashtag", 150, "night"),
    _t("#NHK", "hashtag", 92, "evening"),
    _t("#地震", "hashtag", 180, None, daily=True),
    _t("#台風", "hashtag", 150, "daytime", daily=True),
    _t("#大谷さん", "hashtag", 130, "morning", daily=True),
    _t("#鬼滅の刃", "hashtag", 140, "night"),
    _t("#原神", "hashtag", 120, "night"),
    _t("#にじさんじ", "hashtag", 108, "latenight"),
    _t("#VTuber", "hashtag", 102, "latenight"),
    _t("#推し活", "hashtag", 110, "evening"),
    _t("#おはよう", "hashtag", 125, "morning"),
    _t("#おやすみ", "hashtag", 120, "latenight"),
    _t("#月曜", "hashtag", 90, "morning", weekly=True),
    _t("#金曜日", "hashtag", 115, "evening", weekly=True),
    _t("#土曜日", "hashtag", 108, "daytime", weekly=True),
    _t("#日曜日", "hashtag", 106, "daytime", weekly=True),
    _t("#深夜の真剣お絵描き", "hashtag", 84, "latenight"),
    _t("#写真de一言", "hashtag", 80, "night"),
    _t("#今日の一枚", "hashtag", 92, "evening"),
    _t("#風景写真", "hashtag", 78, "evening"),
    _t("#料理写真", "hashtag", 76, "evening"),
    _t("#お弁当", "hashtag", 88, "morning"),
    _t("#今日のコーデ", "hashtag", 82, "morning"),
    _t("#筋トレ", "hashtag", 90, "morning"),
    _t("#ダイエット", "hashtag", 96, "morning"),
    _t("#読書", "hashtag", 74, "latenight"),
    _t("#勉強垢", "hashtag", 86, "night"),
    _t("#受験生", "hashtag", 94, "night"),
    _t("#お仕事", "hashtag", 80, "morning"),
    _t("#在宅勤務", "hashtag", 72, "morning"),
    _t("#リモート", "hashtag", 70, "morning"),
    _t("#お天気", "hashtag", 68, "morning"),
    _t("#猛暑", "hashtag", 110, "daytime", daily=True),
    _t("#花粉", "hashtag", 100, "morning"),
    _t("#桜", "hashtag", 130, "daytime", weekly=True),
    _t("#花火", "hashtag", 118, "night", weekly=True),
    _t("#初詣", "hashtag", 120, "morning"),
    _t("#年賀状", "hashtag", 96, "morning"),
    _t("#クリスマス", "hashtag", 140, "evening"),
    _t("#ハロウィン", "hashtag", 132, "evening"),
    _t("#バレンタイン", "hashtag", 116, "daytime"),
    _t("#母の日", "hashtag", 108, "morning"),
    _t("#父の日", "hashtag", 102, "morning"),
    _t("#GW", "hashtag", 122, "morning"),
    _t("#夏休み", "hashtag", 114, "morning"),
    _t("#冬休み", "hashtag", 104, "morning"),
    _t("#成人式", "hashtag", 126, "morning"),
    _t("#卒業式", "hashtag", 112, "morning"),
    _t("#入学式", "hashtag", 108, "morning"),
    _t("#入社式", "hashtag", 100, "morning"),
    _t("#忘年会", "hashtag", 98, "evening"),
    _t("#新年会", "hashtag", 94, "evening"),
    _t("#お花見", "hashtag", 106, "daytime", weekly=True),
    _t("#紅葉", "hashtag", 100, "daytime", weekly=True),
    _t("#雪", "hashtag", 108, "morning", daily=True),
    _t("#雨", "hashtag", 92, "morning", daily=True),
    _t("#晴れ", "hashtag", 76, "morning"),
    _t("#夕焼け", "hashtag", 88, "evening"),
    _t("#夜景", "hashtag", 80, "night"),
    _t("#朝活", "hashtag", 84, "morning"),
    _t("#夜活", "hashtag", 72, "latenight"),
    _t("#お昼ごはん", "hashtag", 90, "daytime"),
    _t("#晩ごはん", "hashtag", 94, "evening"),
    _t("#デザート", "hashtag", 74, "evening"),
    _t("#カフェ", "hashtag", 96, "daytime"),
    _t("#パンケーキ", "hashtag", 78, "daytime"),
    _t("#タピオカ", "hashtag", 76, "evening"),
    _t("#焼肉", "hashtag", 82, "evening", weekly=True),
    _t("#寿司", "hashtag", 84, "evening"),
    _t("#ラーメン", "hashtag", 100, "night"),
    _t("#うどん", "hashtag", 78, "daytime"),
    _t("#そば", "hashtag", 70, "evening"),
    _t("#カレー", "hashtag", 80, "evening"),
    _t("#スイーツ", "hashtag", 92, "daytime"),
    _t("#コンビニスイーツ", "hashtag", 88, "daytime"),
    _t("#スタバ", "hashtag", 98, "morning"),
    _t("#マック", "hashtag", 86, "daytime"),
    _t("#ユニクロ", "hashtag", 90, "daytime"),
    _t("#GU", "hashtag", 78, "daytime"),
    _t("#無印", "hashtag", 74, "daytime"),
    _t("#コストコ", "hashtag", 84, "daytime", weekly=True),
    _t("#ドンキ", "hashtag", 76, "night"),
    _t("#PayPay", "hashtag", 82, "daytime"),
    _t("#楽天", "hashtag", 80, "daytime"),
    _t("#Amazon", "hashtag", 86, "evening"),
    _t("#セール", "hashtag", 88, "evening"),
    _t("#福袋", "hashtag", 100, "morning"),
    _t("#初売り", "hashtag", 96, "morning"),
    _t("#ブラックフライデー", "hashtag", 108, "night"),
    _t("#ディズニー", "hashtag", 120, "daytime", weekly=True),
    _t("#USJ", "hashtag", 110, "daytime", weekly=True),
    _t("#ジブリ", "hashtag", 96, "night", weekly=True),
    _t("#旅行", "hashtag", 90, "evening", weekly=True),
    _t("#温泉", "hashtag", 82, "evening", weekly=True),
    _t("#ホテル", "hashtag", 70, "evening"),
    _t("#キャンプ", "hashtag", 88, "daytime", weekly=True),
    _t("#登山", "hashtag", 80, "morning", weekly=True),
    _t("#海", "hashtag", 76, "daytime", weekly=True),
    _t("#山", "hashtag", 68, "morning", weekly=True),
    _t("#川", "hashtag", 64, "daytime"),
    _t("#空", "hashtag", 86, "evening"),
    _t("#雲", "hashtag", 72, "daytime"),
    _t("#虹", "hashtag", 78, "evening", daily=True),
    _t("#星空", "hashtag", 82, "latenight"),
    _t("#月", "hashtag", 88, "night"),
    _t("#満月", "hashtag", 94, "night", weekly=True),
    _t("#新月", "hashtag", 76, "night"),
    _t("#流星群", "hashtag", 90, "latenight", daily=True),
    _t("#皆既月食", "hashtag", 100, "night", daily=True),
    _t("#日食", "hashtag", 96, "morning", daily=True),
    _t("#地震速報", "hashtag", 140, None, daily=True),
    _t("#避難", "hashtag", 110, None, daily=True),
    _t("#警報", "hashtag", 104, "morning", daily=True),
    _t("#熱中症", "hashtag", 100, "daytime", daily=True),
    _t("#インフル", "hashtag", 96, "morning", daily=True),
    _t("#コロナ", "hashtag", 92, "daytime"),
    _t("#ワクチン", "hashtag", 78, "daytime"),
    _t("#医療", "hashtag", 70, "daytime"),
    _t("#介護", "hashtag", 74, "daytime"),
    _t("#育児", "hashtag", 80, "morning"),
    _t("#保育園", "hashtag", 72, "morning"),
    _t("#学校", "hashtag", 78, "morning"),
    _t("#部活", "hashtag", 76, "evening"),
    _t("#高校野球", "hashtag", 120, "daytime", weekly=True),
    _t("#甲子園", "hashtag", 140, "daytime", weekly=True),
    _t("#プロ野球", "hashtag", 130, "night"),
    _t("#Jリーグ", "hashtag", 100, "evening", weekly=True),
    _t("#日本代表", "hashtag", 125, "night", daily=True),
    _t("#プレミアリーグ", "hashtag", 105, "night", weekly=True),
    _t("#CL", "hashtag", 115, "latenight", weekly=True),
    _t("#W杯", "hashtag", 135, "night", daily=True),
    _t("#大相撲", "hashtag", 110, "daytime", weekly=True),
    _t("#F1", "hashtag", 108, "night", weekly=True),
    _t("#テニス", "hashtag", 82, "evening", weekly=True),
    _t("#ゴルフ", "hashtag", 76, "morning", weekly=True),
    _t("#マラソン", "hashtag", 90, "morning", weekly=True),
    _t("#駅伝", "hashtag", 106, "morning", weekly=True),
    _t("#箱根", "hashtag", 112, "morning", weekly=True),
    _t("#バスケ", "hashtag", 78, "evening", weekly=True),
    _t("#NBA", "hashtag", 92, "morning"),
    _t("#ボクシング", "hashtag", 88, "night", weekly=True),
    _t("#卓球", "hashtag", 70, "night", weekly=True),
    _t("#バレー", "hashtag", 72, "evening", weekly=True),
    _t("#フィギュア", "hashtag", 84, "night", weekly=True),
    _t("#オリンピック", "hashtag", 100, "daytime"),
    _t("#パラリンピック", "hashtag", 80, "daytime"),
    _t("#eスポーツ", "hashtag", 76, "latenight"),
    _t("#ゲーム", "hashtag", 82, "night"),
    _t("#アニメ", "hashtag", 90, "night"),
    _t("#漫画", "hashtag", 86, "night"),
    _t("#声優", "hashtag", 80, "evening"),
    _t("#映画", "hashtag", 88, "evening", weekly=True),
    _t("#ドラマ", "hashtag", 92, "night", weekly=True),
    _t("#音楽", "hashtag", 84, "evening"),
    _t("#ライブ", "hashtag", 90, "night", weekly=True),
    _t("#フェス", "hashtag", 82, "daytime", weekly=True),
    _t("#カラオケ", "hashtag", 74, "night"),
    _t("#ギター", "hashtag", 68, "night"),
    _t("#ピアノ", "hashtag", 66, "evening"),
    _t("#ドラム", "hashtag", 62, "night"),
    _t("#ベース", "hashtag", 60, "night"),
    _t("#作曲", "hashtag", 64, "latenight"),
    _t("#DTM", "hashtag", 70, "latenight"),
    _t("#イラスト", "hashtag", 100, "night"),
    _t("#絵描きさんと繋がりたい", "hashtag", 88, "night"),
    _t("#小説", "hashtag", 72, "latenight"),
    _t("#俳句", "hashtag", 60, "morning"),
    _t("#短歌", "hashtag", 58, "morning"),
    _t("#写真", "hashtag", 90, "evening"),
    _t("#カメラ", "hashtag", 78, "evening"),
    _t("#動画", "hashtag", 74, "night"),
    _t("#YouTube", "hashtag", 86, "night"),
    _t("#TikTok", "hashtag", 92, "evening"),
    _t("#Instagram", "hashtag", 76, "evening"),
    _t("#X", "hashtag", 80, "daytime"),
    _t("#Twitter", "hashtag", 72, "daytime"),
    _t("#AI", "hashtag", 96, "daytime"),
    _t("#ChatGPT", "hashtag", 104, "daytime"),
    _t("#生成AI", "hashtag", 88, "daytime"),
    _t("#プログラミング", "hashtag", 82, "latenight"),
    _t("#エンジニア", "hashtag", 78, "latenight"),
    _t("#副業", "hashtag", 84, "night"),
    _t("#投資", "hashtag", 90, "morning"),
    _t("#NISA", "hashtag", 96, "daytime"),
    _t("#仮想通貨", "hashtag", 88, "night"),
    _t("#ビットコイン", "hashtag", 94, "night"),
    _t("#株", "hashtag", 86, "morning"),
    _t("#FX", "hashtag", 78, "morning"),
    _t("#節約", "hashtag", 80, "daytime"),
    _t("#ポイ活", "hashtag", 76, "daytime"),
    _t("#ふるさと納税", "hashtag", 82, "daytime"),
    _t("#転職", "hashtag", 78, "morning"),
    _t("#就活", "hashtag", 90, "morning"),
    _t("#お仕事", "hashtag", 72, "morning"),
    _t("#リモートワーク", "hashtag", 70, "morning"),
    _t("#満員電車", "hashtag", 68, "morning"),
    _t("#通勤", "hashtag", 64, "morning"),
    _t("#残業", "hashtag", 74, "night"),
    _t("#ブラック企業", "hashtag", 70, "night"),
    _t("#働き方改革", "hashtag", 66, "daytime"),
    _t("#ワークライフバランス", "hashtag", 62, "evening"),
    _t("#自己肯定感", "hashtag", 68, "night"),
    _t("#メンタルヘルス", "hashtag", 64, "night"),
    _t("#睡眠", "hashtag", 70, "latenight"),
    _t("#早起き", "hashtag", 66, "morning"),
    _t("#習慣", "hashtag", 60, "morning"),
    _t("#目標", "hashtag", 62, "morning"),
    _t("#頑張ろう", "hashtag", 72, "morning"),
    _t("#応援", "hashtag", 68, "evening"),
    _t("#ありがとう", "hashtag", 74, "evening"),
    _t("#おめでとう", "hashtag", 76, "evening"),
    _t("#誕生日", "hashtag", 80, "evening"),
    _t("#HappyBirthday", "hashtag", 70, "evening"),
    _t("#記念日", "hashtag", 64, "evening"),
    _t("#プロポーズ", "hashtag", 62, "night"),
    _t("#結婚式", "hashtag", 70, "daytime", weekly=True),
    _t("#新婚", "hashtag", 60, "evening"),
    _t("#家族", "hashtag", 68, "evening"),
    _t("#友達", "hashtag", 64, "evening"),
    _t("#恋人", "hashtag", 60, "night"),
    _t("#推し", "hashtag", 86, "night"),
    _t("#推し活", "hashtag", 84, "evening"),
    _t("#尊い", "hashtag", 70, "night"),
    _t("#かわいい", "hashtag", 82, "evening"),
    _t("#かっこいい", "hashtag", 72, "night"),
    _t("#美しい", "hashtag", 66, "evening"),
    _t("#癒し", "hashtag", 74, "night"),
    _t("#元気", "hashtag", 62, "morning"),
    _t("#笑顔", "hashtag", 68, "evening"),
    _t("#幸せ", "hashtag", 70, "night"),
    _t("#感謝", "hashtag", 66, "evening"),
    _t("#希望", "hashtag", 60, "morning"),
    _t("#未来", "hashtag", 58, "morning"),
    _t("#夢", "hashtag", 64, "latenight"),
    _t("#挑戦", "hashtag", 62, "morning"),
    _t("#努力", "hashtag", 60, "night"),
    _t("#成功", "hashtag", 58, "morning"),
    _t("#失敗", "hashtag", 56, "night"),
    _t("#学び", "hashtag", 64, "morning"),
    _t("#勉強", "hashtag", 72, "night"),
    _t("#資格", "hashtag", 60, "daytime"),
    _t("#英会話", "hashtag", 58, "morning"),
    _t("#TOEIC", "hashtag", 66, "morning"),
    _t("#TOEFL", "hashtag", 58, "morning"),
    _t("#IELTS", "hashtag", 56, "morning"),
    _t("#留学", "hashtag", 62, "daytime"),
    _t("#海外", "hashtag", 68, "evening"),
    _t("#国際", "hashtag", 60, "daytime"),
    _t("#平和", "hashtag", 64, "evening"),
    _t("#戦争", "hashtag", 70, "daytime", daily=True),
    _t("#紛争", "hashtag", 58, "daytime"),
    _t("#難民", "hashtag", 60, "daytime"),
    _t("#支援", "hashtag", 62, "evening"),
    _t("#寄付", "hashtag", 58, "evening"),
    _t("#ボランティア", "hashtag", 56, "daytime", weekly=True),
    _t("#SDGs", "hashtag", 64, "daytime"),
    _t("#環境", "hashtag", 62, "daytime"),
    _t("#気候変動", "hashtag", 68, "daytime", daily=True),
    _t("#温暖化", "hashtag", 60, "daytime"),
    _t("#脱炭素", "hashtag", 58, "daytime"),
    _t("#再エネ", "hashtag", 56, "daytime"),
    _t("#太陽光", "hashtag", 58, "daytime"),
    _t("#風力", "hashtag", 54, "daytime"),
    _t("#原発", "hashtag", 66, "daytime", daily=True),
    _t("#電力", "hashtag", 58, "daytime"),
    _t("#エネルギー", "hashtag", 60, "daytime"),
    _t("#ガソリン", "hashtag", 62, "morning"),
    _t("#電気代", "hashtag", 64, "daytime"),
    _t("#水道代", "hashtag", 54, "daytime"),
    _t("#物価", "hashtag", 70, "daytime"),
    _t("#値上げ", "hashtag", 76, "morning"),
    _t("#賃上げ", "hashtag", 68, "daytime"),
    _t("#年金", "hashtag", 72, "daytime"),
    _t("#税金", "hashtag", 66, "daytime"),
    _t("#確定申告", "hashtag", 80, "morning"),
    _t("#マイナンバー", "hashtag", 70, "daytime"),
    _t("#保険", "hashtag", 58, "daytime"),
    _t("#住宅ローン", "hashtag", 62, "daytime"),
    _t("#家賃", "hashtag", 60, "daytime"),
    _t("#引っ越し", "hashtag", 64, "daytime"),
    _t("#新生活", "hashtag", 72, "morning"),
    _t("#一人暮らし", "hashtag", 66, "night"),
    _t("#実家", "hashtag", 56, "evening"),
    _t("#家族旅行", "hashtag", 60, "daytime", weekly=True),
    _t("#帰省", "hashtag", 74, "morning", weekly=True),
    _t("#Uターン", "hashtag", 58, "evening", weekly=True),
    _t("#渋滞", "hashtag", 78, "evening", daily=True, weekly=True),
    _t("#新幹線", "hashtag", 84, "morning", daily=True),
    _t("#飛行機", "hashtag", 70, "daytime", daily=True),
    _t("#空港", "hashtag", 62, "morning"),
    _t("#電車", "hashtag", 76, "morning"),
    _t("#バス", "hashtag", 60, "morning"),
    _t("#車", "hashtag", 68, "daytime"),
    _t("#バイク", "hashtag", 62, "daytime"),
    _t("#自転車", "hashtag", 64, "morning"),
    _t("#ウォーキング", "hashtag", 58, "morning"),
    _t("#ランニング", "hashtag", 66, "morning"),
    _t("#ジョギング", "hashtag", 56, "morning"),
    _t("#ジム", "hashtag", 62, "evening"),
    _t("#ヨガ", "hashtag", 58, "morning"),
    _t("#ピラティス", "hashtag", 54, "morning"),
    _t("#ストレッチ", "hashtag", 56, "night"),
    _t("#マッサージ", "hashtag", 54, "evening"),
    _t("#整体", "hashtag", 50, "daytime"),
    _t("#病院", "hashtag", 64, "morning"),
    _t("#歯医者", "hashtag", 56, "daytime"),
    _t("#眼科", "hashtag", 52, "daytime"),
    _t("#皮膚科", "hashtag", 54, "daytime"),
    _t("#耳鼻科", "hashtag", 52, "daytime"),
    _t("#内科", "hashtag", 50, "daytime"),
    _t("#小児科", "hashtag", 54, "morning"),
    _t("#産婦人科", "hashtag", 52, "daytime"),
    _t("#美容", "hashtag", 76, "evening"),
    _t("#コスメ", "hashtag", 80, "evening"),
    _t("#メイク", "hashtag", 74, "morning"),
    _t("#スキンケア", "hashtag", 70, "night"),
    _t("#ヘア", "hashtag", 62, "daytime"),
    _t("#ネイル", "hashtag", 64, "evening"),
    _t("#ファッション", "hashtag", 78, "evening"),
    _t("#コーデ", "hashtag", 82, "morning"),
    _t("#洋服", "hashtag", 60, "daytime"),
    _t("#靴", "hashtag", 56, "daytime"),
    _t("#バッグ", "hashtag", 58, "daytime"),
    _t("#アクセサリー", "hashtag", 54, "evening"),
    _t("#時計", "hashtag", 56, "daytime"),
    _t("#メガネ", "hashtag", 52, "daytime"),
    _t("#コンタクト", "hashtag", 50, "morning"),
    _t("#香水", "hashtag", 54, "evening"),
    _t("#日用品", "hashtag", 56, "daytime"),
    _t("#雑貨", "hashtag", 58, "daytime"),
    _t("#インテリア", "hashtag", 62, "evening"),
    _t("#家具", "hashtag", 54, "daytime"),
    _t("#家電", "hashtag", 60, "daytime"),
    _t("#掃除", "hashtag", 58, "morning"),
    _t("#洗濯", "hashtag", 62, "morning"),
    _t("#収納", "hashtag", 56, "daytime"),
    _t("#断捨離", "hashtag", 58, "daytime", weekly=True),
    _t("#DIY", "hashtag", 54, "daytime", weekly=True),
    _t("#ハンドメイド", "hashtag", 60, "evening"),
    _t("#手作り", "hashtag", 56, "evening"),
    _t("#お菓子作り", "hashtag", 54, "daytime", weekly=True),
    _t("#パン作り", "hashtag", 52, "morning", weekly=True),
    _t("#料理", "hashtag", 72, "evening"),
    _t("#自炊", "hashtag", 64, "evening"),
    _t("#外食", "hashtag", 60, "evening", weekly=True),
    _t("#テイクアウト", "hashtag", 56, "evening"),
    _t("#デリバリー", "hashtag", 54, "evening"),
    _t("#UberEats", "hashtag", 58, "night"),
    _t("#出前館", "hashtag", 50, "night"),
    _t("#コンビニ飯", "hashtag", 56, "daytime"),
    _t("#お弁当", "hashtag", 68, "morning"),
    _t("#給食", "hashtag", 52, "daytime"),
    _t("#学食", "hashtag", 48, "daytime"),
    _t("#社員食堂", "hashtag", 46, "daytime"),
    _t("#カフェ巡り", "hashtag", 58, "daytime", weekly=True),
    _t("#喫茶店", "hashtag", 54, "morning"),
    _t("#レストラン", "hashtag", 56, "evening"),
    _t("#居酒屋", "hashtag", 66, "night", weekly=True),
    _t("#バー", "hashtag", 52, "night"),
    _t("#クラブ", "hashtag", 48, "latenight", weekly=True),
    _t("#カラオケ", "hashtag", 58, "night", weekly=True),
    _t("#ボウリング", "hashtag", 44, "evening", weekly=True),
    _t("#ビリヤード", "hashtag", 40, "night"),
    _t("#ダーツ", "hashtag", 42, "night"),
    _t("#ゲームセンター", "hashtag", 50, "evening", weekly=True),
    _t("#映画館", "hashtag", 56, "evening", weekly=True),
    _t("#劇場", "hashtag", 48, "evening", weekly=True),
    _t("#美術館", "hashtag", 52, "daytime", weekly=True),
    _t("#博物館", "hashtag", 50, "daytime", weekly=True),
    _t("#水族館", "hashtag", 54, "daytime", weekly=True),
    _t("#動物園", "hashtag", 52, "daytime", weekly=True),
    _t("#植物園", "hashtag", 46, "daytime", weekly=True),
    _t("#公園", "hashtag", 56, "morning", weekly=True),
    _t("#散歩", "hashtag", 58, "morning"),
    _t("#ピクニック", "hashtag", 50, "daytime", weekly=True),
    _t("#バーベキュー", "hashtag", 52, "daytime", weekly=True),
    _t("#花火大会", "hashtag", 70, "night", weekly=True),
    _t("#祭り", "hashtag", 66, "evening", weekly=True),
    _t("#夏祭り", "hashtag", 72, "evening", weekly=True),
    _t("#盆踊り", "hashtag", 54, "night", weekly=True),
    _t("#縁日", "hashtag", 48, "evening", weekly=True),
    _t("#屋台", "hashtag", 46, "evening", weekly=True),
    _t("#神社", "hashtag", 56, "morning", weekly=True),
    _t("#お寺", "hashtag", 52, "morning", weekly=True),
    _t("#御朱印", "hashtag", 48, "daytime", weekly=True),
    _t("#パワースポット", "hashtag", 50, "daytime"),
    _t("#占い", "hashtag", 58, "morning"),
    _t("#星座", "hashtag", 52, "morning"),
    _t("#運勢", "hashtag", 54, "morning"),
    _t("#タロット", "hashtag", 48, "night"),
    _t("#風水", "hashtag", 46, "daytime"),
    _t("#スピリチュアル", "hashtag", 50, "night"),
    _t("#瞑想", "hashtag", 48, "morning"),
    _t("#マインドフルネス", "hashtag", 46, "morning"),
    _t("#ポジティブ", "hashtag", 50, "morning"),
    _t("#モチベーション", "hashtag", 52, "morning"),
    _t("#やる気", "hashtag", 54, "morning"),
    _t("#集中", "hashtag", 48, "morning"),
    _t("#習慣化", "hashtag", 46, "morning"),
    _t("#継続", "hashtag", 48, "morning"),
    _t("#記録", "hashtag", 44, "evening"),
    _t("#日記", "hashtag", 52, "latenight"),
    _t("#ブログ", "hashtag", 50, "night"),
    _t("#note", "hashtag", 54, "night"),
    _t("#Voicy", "hashtag", 44, "morning"),
    _t("#Podcast", "hashtag", 48, "morning"),
    _t("#ラジオ", "hashtag", 56, "night"),
    _t("#深夜ラジオ", "hashtag", 52, "latenight"),
    _t("#ANN", "hashtag", 48, "latenight", weekly=True),
    _t("#オールナイトニッポン", "hashtag", 54, "latenight", weekly=True),
    _t("#radiko", "hashtag", 46, "night"),
]

# --------------------------------------------------------------------------- #
# 英語 / グローバルプール
# --------------------------------------------------------------------------- #

_EN: list[dict] = [
    _t("Taylor Swift", "entertainment", 190, "evening", daily=True),
    _t("Beyoncé", "entertainment", 150, "night", daily=True),
    _t("Drake", "entertainment", 140, "latenight", daily=True),
    _t("Kendrick Lamar", "entertainment", 135, "night", daily=True),
    _t("Sabrina Carpenter", "entertainment", 145, "evening", daily=True),
    _t("Billie Eilish", "entertainment", 130, "night", daily=True),
    _t("Olivia Rodrigo", "entertainment", 118, "evening", daily=True),
    _t("Ariana Grande", "entertainment", 128, "evening", daily=True),
    _t("The Weeknd", "entertainment", 122, "latenight", daily=True),
    _t("Dua Lipa", "entertainment", 116, "evening", daily=True),
    _t("Bad Bunny", "entertainment", 140, "night", daily=True),
    _t("BTS", "entertainment", 175, "evening"),
    _t("BLACKPINK", "entertainment", 150, "evening"),
    _t("NewJeans", "entertainment", 120, "evening", daily=True),
    _t("Stray Kids", "entertainment", 118, "night", daily=True),
    _t("SEVENTEEN", "entertainment", 116, "night", daily=True),
    _t("Grammys", "entertainment", 160, "night", weekly=True),
    _t("Billboard", "entertainment", 110, "daytime"),
    _t("Coachella", "entertainment", 145, "night", weekly=True),
    _t("Super Bowl", "sports", 200, "night", weekly=True),
    _t("Halftime Show", "entertainment", 150, "night", weekly=True),
    _t("NBA", "sports", 175, "night"),
    _t("LeBron", "sports", 140, "night", daily=True),
    _t("Steph Curry", "sports", 130, "night", daily=True),
    _t("Lakers", "sports", 145, "night", daily=True),
    _t("Celtics", "sports", 132, "night", daily=True),
    _t("Warriors", "sports", 128, "night", daily=True),
    _t("NFL", "sports", 165, "night", weekly=True),
    _t("Chiefs", "sports", 148, "night", weekly=True),
    _t("Patrick Mahomes", "sports", 138, "night", daily=True),
    _t("MLB", "sports", 150, "night"),
    _t("Dodgers", "sports", 170, "night", daily=True),
    _t("Shohei Ohtani", "sports", 185, "morning", daily=True),
    _t("Yankees", "sports", 142, "night", daily=True),
    _t("World Series", "sports", 175, "night", weekly=True),
    _t("Premier League", "sports", 160, "night", weekly=True),
    _t("Manchester City", "sports", 138, "night", weekly=True),
    _t("Arsenal", "sports", 140, "night", weekly=True),
    _t("Liverpool", "sports", 146, "night", weekly=True),
    _t("Real Madrid", "sports", 158, "night", daily=True),
    _t("Barcelona", "sports", 152, "night", daily=True),
    _t("Champions League", "sports", 168, "night", weekly=True),
    _t("Messi", "sports", 172, "night", daily=True),
    _t("Cristiano Ronaldo", "sports", 166, "night", daily=True),
    _t("Mbappé", "sports", 144, "night", daily=True),
    _t("Haaland", "sports", 136, "night", daily=True),
    _t("World Cup", "sports", 210, "night", daily=True),
    _t("F1", "sports", 148, "night", weekly=True),
    _t("Verstappen", "sports", 126, "night", weekly=True),
    _t("Hamilton", "sports", 120, "night", weekly=True),
    _t("US Open", "sports", 132, "night", weekly=True),
    _t("Wimbledon", "sports", 138, "night", weekly=True),
    _t("Djokovic", "sports", 118, "night", daily=True),
    _t("Alcaraz", "sports", 124, "night", daily=True),
    _t("Sinner", "sports", 122, "night", daily=True),
    _t("The Masters", "sports", 110, "night", weekly=True),
    _t("UFC", "sports", 130, "latenight", weekly=True),
    _t("Olympics", "sports", 165, "daytime"),
    _t("One Piece", "anime_game", 160, "night"),
    _t("Demon Slayer", "anime_game", 168, "night"),
    _t("Jujutsu Kaisen", "anime_game", 155, "latenight"),
    _t("Chainsaw Man", "anime_game", 140, "latenight", daily=True),
    _t("Frieren", "anime_game", 128, "night", daily=True),
    _t("SPY×FAMILY", "anime_game", 122, "night", daily=True),
    _t("My Hero Academia", "anime_game", 118, "night"),
    _t("Dragon Ball", "anime_game", 130, "night"),
    _t("Naruto", "anime_game", 116, "night"),
    _t("Attack on Titan", "anime_game", 124, "latenight"),
    _t("Studio Ghibli", "anime_game", 138, "evening", daily=True),
    _t("Miyazaki", "anime_game", 110, "evening", daily=True),
    _t("Pokémon", "anime_game", 165, "evening"),
    _t("Genshin Impact", "anime_game", 158, "night"),
    _t("Honkai Star Rail", "anime_game", 132, "night", daily=True),
    _t("Fortnite", "anime_game", 150, "night"),
    _t("Valorant", "anime_game", 136, "latenight"),
    _t("Apex Legends", "anime_game", 124, "latenight"),
    _t("Minecraft", "anime_game", 146, "evening"),
    _t("GTA 6", "anime_game", 190, "night", daily=True),
    _t("Nintendo Switch 2", "anime_game", 160, "daytime", daily=True),
    _t("PlayStation", "tech", 128, "evening", daily=True),
    _t("Xbox", "tech", 120, "evening", daily=True),
    _t("Steam", "anime_game", 116, "latenight"),
    _t("Elden Ring", "anime_game", 134, "night", daily=True),
    _t("Monster Hunter", "anime_game", 142, "night", daily=True),
    _t("Zelda", "anime_game", 130, "night"),
    _t("Mario", "anime_game", 148, "evening"),
    _t("Call of Duty", "anime_game", 138, "night", daily=True),
    _t("EA FC", "anime_game", 126, "night", daily=True),
    _t("Marvel", "entertainment", 158, "evening", daily=True),
    _t("Spider-Man", "entertainment", 150, "evening", daily=True),
    _t("Avengers", "entertainment", 146, "evening", daily=True),
    _t("Deadpool", "entertainment", 132, "night", daily=True),
    _t("Batman", "entertainment", 128, "night", daily=True),
    _t("Superman", "entertainment", 130, "night", daily=True),
    _t("Star Wars", "entertainment", 154, "night", daily=True),
    _t("Jedi", "entertainment", 112, "night", daily=True),
    _t("Harry Potter", "entertainment", 140, "evening", daily=True),
    _t("HBO", "entertainment", 118, "night"),
    _t("Netflix", "lifestyle", 152, "night"),
    _t("Stranger Things", "entertainment", 148, "night", daily=True),
    _t("Wednesday", "entertainment", 136, "night", daily=True),
    _t("Squid Game", "entertainment", 158, "night", daily=True),
    _t("The Last of Us", "entertainment", 142, "night", daily=True),
    _t("House of the Dragon", "entertainment", 134, "night", daily=True),
    _t("Shōgun", "entertainment", 126, "night", daily=True),
    _t("White Lotus", "entertainment", 118, "night", daily=True),
    _t("Severance", "entertainment", 114, "night", daily=True),
    _t("The Bear", "entertainment", 108, "night", daily=True),
    _t("Box Office", "entertainment", 104, "daytime", daily=True),
    _t("Oscars", "entertainment", 170, "night", weekly=True),
    _t("Golden Globes", "entertainment", 140, "night", weekly=True),
    _t("Emmys", "entertainment", 132, "night", weekly=True),
    _t("Cannes", "entertainment", 118, "evening", weekly=True),
    _t("Timothée Chalamet", "entertainment", 128, "evening", daily=True),
    _t("Zendaya", "entertainment", 130, "evening", daily=True),
    _t("Tom Holland", "entertainment", 122, "evening", daily=True),
    _t("Leonardo DiCaprio", "entertainment", 118, "night", daily=True),
    _t("Brad Pitt", "entertainment", 112, "night", daily=True),
    _t("Tom Cruise", "entertainment", 120, "night", daily=True),
    _t("Kim Kardashian", "entertainment", 148, "evening", daily=True),
    _t("Kanye", "entertainment", 142, "night", daily=True),
    _t("Justin Bieber", "entertainment", 118, "evening", daily=True),
    _t("Selena Gomez", "entertainment", 126, "evening", daily=True),
    _t("Elon Musk", "tech", 210, "night", daily=True),
    _t("Tesla", "tech", 178, "night", daily=True),
    _t("SpaceX", "tech", 156, "night", daily=True),
    _t("Grok", "tech", 148, "night", daily=True),
    _t("xAI", "tech", 130, "daytime", daily=True),
    _t("OpenAI", "tech", 190, "daytime", daily=True),
    _t("ChatGPT", "tech", 185, "daytime"),
    _t("GPT-5", "tech", 150, "daytime", daily=True),
    _t("Sora", "tech", 132, "evening", daily=True),
    _t("Claude", "tech", 118, "daytime", daily=True),
    _t("Anthropic", "tech", 122, "daytime", daily=True),
    _t("Gemini", "tech", 138, "daytime", daily=True),
    _t("Google", "tech", 156, "daytime"),
    _t("Apple", "tech", 172, "evening", daily=True),
    _t("iPhone", "tech", 180, "evening", daily=True),
    _t("MacBook", "tech", 124, "night", daily=True),
    _t("iOS", "tech", 130, "daytime", daily=True),
    _t("Android", "tech", 118, "daytime"),
    _t("Samsung", "tech", 126, "daytime", daily=True),
    _t("Microsoft", "tech", 140, "daytime"),
    _t("Windows", "tech", 122, "daytime", daily=True),
    _t("Copilot", "tech", 116, "daytime", daily=True),
    _t("Amazon", "tech", 134, "evening"),
    _t("AWS", "tech", 108, "daytime"),
    _t("Meta", "tech", 128, "daytime", daily=True),
    _t("Instagram", "lifestyle", 146, "evening"),
    _t("TikTok", "lifestyle", 168, "evening"),
    _t("YouTube", "lifestyle", 160, "evening"),
    _t("Nvidia", "tech", 152, "morning", daily=True),
    _t("AMD", "tech", 108, "morning", daily=True),
    _t("Intel", "tech", 104, "morning", daily=True),
    _t("TSMC", "tech", 98, "morning", daily=True),
    _t("AI", "tech", 200, "daytime"),
    _t("AGI", "tech", 110, "night", daily=True),
    _t("GPU", "tech", 106, "daytime"),
    _t("Quantum Computing", "tech", 100, "daytime", daily=True),
    _t("Cyberattack", "news", 128, "daytime", daily=True),
    _t("Data Breach", "news", 122, "daytime", daily=True),
    _t("Outage", "tech", 138, "daytime", daily=True),
    _t("Self-Driving", "tech", 102, "daytime", daily=True),
    _t("Robotics", "tech", 96, "daytime"),
    _t("Drone", "tech", 90, "daytime", daily=True),
    _t("Starlink", "tech", 104, "night", daily=True),
    _t("Donald Trump", "news", 230, "daytime", daily=True),
    _t("Trump", "news", 225, "daytime", daily=True),
    _t("White House", "news", 168, "daytime", daily=True),
    _t("President", "news", 160, "daytime", daily=True),
    _t("Congress", "news", 138, "daytime"),
    _t("Senate", "news", 134, "daytime"),
    _t("Supreme Court", "news", 146, "daytime", daily=True),
    _t("Election", "news", 190, "daytime", daily=True),
    _t("Voting", "news", 140, "daytime", daily=True),
    _t("Democrats", "news", 132, "daytime"),
    _t("Republicans", "news", 130, "daytime"),
    _t("Government Shutdown", "news", 158, "daytime", daily=True),
    _t("Tariffs", "finance", 166, "morning", daily=True),
    _t("Trade War", "finance", 140, "morning", daily=True),
    _t("Federal Reserve", "finance", 152, "daytime", daily=True),
    _t("Fed", "finance", 148, "morning"),
    _t("Powell", "finance", 124, "morning", daily=True),
    _t("Interest Rates", "finance", 136, "daytime"),
    _t("Rate Cut", "finance", 144, "daytime", daily=True),
    _t("Inflation", "finance", 142, "daytime"),
    _t("CPI", "finance", 118, "morning", daily=True),
    _t("GDP", "finance", 112, "morning", daily=True),
    _t("Recession", "finance", 138, "daytime", daily=True),
    _t("Stock Market", "finance", 170, "morning"),
    _t("S&P 500", "finance", 146, "morning"),
    _t("Nasdaq", "finance", 138, "morning"),
    _t("Dow Jones", "finance", 132, "morning"),
    _t("Wall Street", "finance", 128, "morning"),
    _t("Market Crash", "finance", 154, "morning", daily=True),
    _t("Bitcoin", "finance", 192, "night", daily=True),
    _t("Crypto", "finance", 168, "night"),
    _t("Ethereum", "finance", 130, "night", daily=True),
    _t("Solana", "finance", 112, "night", daily=True),
    _t("XRP", "finance", 118, "night", daily=True),
    _t("Dogecoin", "finance", 120, "night", daily=True),
    _t("NFT", "finance", 96, "night"),
    _t("DeFi", "finance", 88, "latenight"),
    _t("Stablecoin", "finance", 92, "daytime"),
    _t("Earnings", "finance", 126, "evening", daily=True),
    _t("IPO", "finance", 108, "daytime", daily=True),
    _t("Layoffs", "news", 134, "daytime", daily=True),
    _t("Housing Market", "finance", 104, "daytime"),
    _t("Mortgage Rates", "finance", 98, "daytime"),
    _t("Gas Prices", "finance", 110, "morning"),
    _t("Gold", "finance", 116, "morning", daily=True),
    _t("Oil", "finance", 122, "morning", daily=True),
    _t("Earthquake", "news", 190, None, daily=True),
    _t("Tsunami", "news", 150, None, daily=True),
    _t("Hurricane", "news", 185, "daytime", daily=True),
    _t("Tornado", "news", 148, "evening", daily=True),
    _t("Wildfire", "news", 162, "daytime", daily=True),
    _t("Flood", "news", 138, "morning", daily=True),
    _t("Heat Wave", "news", 132, "daytime", daily=True),
    _t("Blizzard", "news", 126, "morning", daily=True),
    _t("Snow", "news", 120, "morning", daily=True),
    _t("Storm", "news", 136, "evening", daily=True),
    _t("Weather", "lifestyle", 118, "morning"),
    _t("Fire", "news", 124, "night", daily=True),
    _t("Crash", "news", 130, "daytime", daily=True),
    _t("Shooting", "news", 158, "evening", daily=True),
    _t("Arrest", "news", 142, "evening", daily=True),
    _t("Trial", "news", 136, "daytime", daily=True),
    _t("Verdict", "news", 128, "daytime", daily=True),
    _t("Lawsuit", "news", 122, "daytime", daily=True),
    _t("Investigation", "news", 118, "daytime", daily=True),
    _t("Missing", "news", 112, "evening", daily=True),
    _t("Ukraine", "news", 188, "daytime", daily=True),
    _t("Russia", "news", 182, "daytime", daily=True),
    _t("Putin", "news", 156, "daytime", daily=True),
    _t("Zelensky", "news", 148, "daytime", daily=True),
    _t("Ceasefire", "news", 142, "daytime", daily=True),
    _t("NATO", "news", 130, "daytime"),
    _t("Israel", "news", 176, "daytime", daily=True),
    _t("Gaza", "news", 172, "daytime", daily=True),
    _t("Hamas", "news", 140, "daytime", daily=True),
    _t("Hezbollah", "news", 118, "daytime", daily=True),
    _t("Iran", "news", 154, "daytime", daily=True),
    _t("China", "news", 166, "daytime", daily=True),
    _t("Taiwan", "news", 128, "daytime", daily=True),
    _t("North Korea", "news", 134, "daytime", daily=True),
    _t("India", "news", 142, "daytime"),
    _t("Modi", "news", 120, "daytime", daily=True),
    _t("UN", "news", 112, "daytime"),
    _t("Sanctions", "news", 108, "daytime", daily=True),
    _t("Immigration", "news", 146, "daytime", daily=True),
    _t("Border", "news", 124, "daytime", daily=True),
    _t("Protest", "news", 138, "evening", daily=True),
    _t("Strike", "news", 116, "morning", daily=True),
    _t("Riot", "news", 108, "night", daily=True),
    _t("Pandemic", "news", 114, "daytime"),
    _t("Vaccine", "news", 106, "daytime"),
    _t("Flu Season", "news", 122, "morning", daily=True),
    _t("Healthcare", "news", 102, "daytime"),
    _t("Medicare", "news", 96, "daytime"),
    _t("Climate Change", "news", 126, "daytime", daily=True),
    _t("Global Warming", "news", 110, "daytime"),
    _t("Extreme Weather", "news", 118, "daytime", daily=True),
    _t("Carbon Emissions", "news", 92, "daytime"),
    _t("Renewable Energy", "news", 88, "daytime"),
    _t("Solar Power", "news", 86, "daytime"),
    _t("EV", "tech", 124, "daytime", daily=True),
    _t("Electric Vehicle", "tech", 108, "daytime"),
    _t("Byron", "other", 60, "night", daily=True, count="none"),
    _t("Breaking News", "news", 150, "daytime", daily=True),
    _t("Viral", "lifestyle", 128, "evening", daily=True),
    _t("Trending", "other", 110, "evening"),
    _t("Meme", "lifestyle", 122, "night", daily=True),
    _t("TikTok Made Me Buy It", "lifestyle", 96, "evening", daily=True),
    _t("Black Friday", "lifestyle", 158, "night"),
    _t("Cyber Monday", "lifestyle", 140, "daytime"),
    _t("Prime Day", "lifestyle", 138, "daytime"),
    _t("Sale", "lifestyle", 120, "evening"),
    _t("Amazon Deals", "lifestyle", 112, "evening"),
    _t("Walmart", "lifestyle", 108, "daytime"),
    _t("Costco", "lifestyle", 106, "daytime", weekly=True),
    _t("Target", "lifestyle", 100, "daytime"),
    _t("Starbucks", "lifestyle", 142, "morning", daily=True),
    _t("McDonald's", "lifestyle", 138, "daytime", daily=True),
    _t("Chipotle", "lifestyle", 116, "daytime", daily=True),
    _t("Chick-fil-A", "lifestyle", 112, "daytime", daily=True),
    _t("Taco Bell", "lifestyle", 104, "night", daily=True),
    _t("Pizza", "lifestyle", 110, "evening"),
    _t("Burger", "lifestyle", 98, "evening"),
    _t("Sushi", "lifestyle", 92, "evening"),
    _t("Ramen", "lifestyle", 96, "night"),
    _t("Brunch", "lifestyle", 90, "morning", weekly=True),
    _t("Coffee", "lifestyle", 108, "morning"),
    _t("Recipe", "lifestyle", 88, "evening"),
    _t("Meal Prep", "lifestyle", 82, "morning", weekly=True),
    _t("Gym", "lifestyle", 94, "morning"),
    _t("Workout", "lifestyle", 88, "morning"),
    _t("Running", "lifestyle", 80, "morning"),
    _t("Marathon", "sports", 106, "morning", weekly=True),
    _t("Yoga", "lifestyle", 76, "morning"),
    _t("Mental Health", "lifestyle", 92, "night"),
    _t("Self Care", "lifestyle", 84, "night"),
    _t("Sleep", "lifestyle", 78, "latenight"),
    _t("Disney", "lifestyle", 156, "daytime", weekly=True),
    _t("Disney+", "lifestyle", 122, "night"),
    _t("Universal Studios", "lifestyle", 108, "daytime", weekly=True),
    _t("Halloween", "lifestyle", 178, "evening"),
    _t("Christmas", "lifestyle", 190, "evening"),
    _t("Thanksgiving", "lifestyle", 182, "daytime"),
    _t("New Year", "lifestyle", 170, "night"),
    _t("Valentine's Day", "lifestyle", 148, "evening"),
    _t("July 4th", "lifestyle", 152, "daytime"),
    _t("Super Bowl Sunday", "sports", 165, "daytime", weekly=True),
    _t("March Madness", "sports", 148, "night", weekly=True),
    _t("Playoffs", "sports", 140, "night", weekly=True),
    _t("Finals", "sports", 134, "night", weekly=True),
    _t("Draft", "sports", 116, "night", weekly=True),
    _t("Trade Deadline", "sports", 108, "daytime", daily=True),
    _t("Injury", "sports", 112, "night", daily=True),
    _t("Coach", "sports", 90, "night", daily=True),
    _t("Referee", "sports", 88, "night", daily=True),
    _t("VAR", "sports", 96, "night", daily=True),
    _t("Transfer", "sports", 118, "daytime", daily=True),
    _t("Transfer Window", "sports", 124, "daytime"),
    _t("Golden Boot", "sports", 92, "night", weekly=True),
    _t("Ballon d'Or", "sports", 130, "night", weekly=True),
    _t("FIFA", "sports", 122, "daytime"),
    _t("UEFA", "sports", 110, "night", weekly=True),
    _t("#NFL", "hashtag", 120, "night", weekly=True),
    _t("#NBA", "hashtag", 118, "night"),
    _t("#MLB", "hashtag", 116, "night"),
    _t("#UCL", "hashtag", 124, "night", weekly=True),
    _t("#F1", "hashtag", 110, "night", weekly=True),
    _t("#AI", "hashtag", 130, "daytime"),
    _t("#ChatGPT", "hashtag", 118, "daytime"),
    _t("#OpenAI", "hashtag", 112, "daytime"),
    _t("#Bitcoin", "hashtag", 122, "night"),
    _t("#Crypto", "hashtag", 108, "night"),
    _t("#BreakingNews", "hashtag", 132, "daytime", daily=True),
    _t("#Election", "hashtag", 126, "daytime", daily=True),
    _t("#Trump", "hashtag", 140, "daytime", daily=True),
    _t("#TaylorSwift", "hashtag", 148, "evening", daily=True),
    _t("#BTS", "hashtag", 138, "evening"),
    _t("#BLACKPINK", "hashtag", 128, "evening"),
    _t("#Kpop", "hashtag", 116, "night"),
    _t("#Marvel", "hashtag", 122, "evening", daily=True),
    _t("#StarWars", "hashtag", 118, "night", daily=True),
    _t("#Netflix", "hashtag", 114, "night"),
    _t("#Gaming", "hashtag", 120, "night"),
    _t("#Anime", "hashtag", 126, "night"),
    _t("#OnePiece", "hashtag", 118, "night"),
    _t("#DemonSlayer", "hashtag", 112, "night"),
    _t("#GenshinImpact", "hashtag", 108, "night"),
    _t("#Fortnite", "hashtag", 110, "night"),
    _t("#GTA6", "hashtag", 132, "night", daily=True),
    _t("#NintendoSwitch2", "hashtag", 114, "daytime", daily=True),
    _t("#PlayStation", "hashtag", 104, "evening", daily=True),
    _t("#iPhone", "hashtag", 116, "evening", daily=True),
    _t("#Apple", "hashtag", 110, "evening", daily=True),
    _t("#Tesla", "hashtag", 120, "night", daily=True),
    _t("#SpaceX", "hashtag", 106, "night", daily=True),
    _t("#ElonMusk", "hashtag", 124, "night", daily=True),
    _t("#MondayMotivation", "hashtag", 108, "morning", weekly=True),
    _t("#MotivationMonday", "hashtag", 96, "morning", weekly=True),
    _t("#ThrowbackThursday", "hashtag", 102, "morning", weekly=True),
    _t("#TBT", "hashtag", 94, "morning", weekly=True),
    _t("#FlashbackFriday", "hashtag", 90, "morning", weekly=True),
    _t("#WeekendVibes", "hashtag", 100, "evening", weekly=True),
    _t("#SundayFunday", "hashtag", 92, "daytime", weekly=True),
    _t("#GoodMorning", "hashtag", 120, "morning"),
    _t("#GoodNight", "hashtag", 108, "latenight"),
    _t("#SelfieSunday", "hashtag", 84, "morning", weekly=True),
    _t("#OOTD", "hashtag", 88, "morning"),
    _t("#Fitness", "hashtag", 86, "morning"),
    _t("#GymLife", "hashtag", 78, "morning"),
    _t("#Healthy", "hashtag", 76, "morning"),
    _t("#Foodie", "hashtag", 92, "evening"),
    _t("#FoodPorn", "hashtag", 84, "evening"),
    _t("#Recipe", "hashtag", 74, "evening"),
    _t("#Cooking", "hashtag", 72, "evening"),
    _t("#Baking", "hashtag", 68, "evening", weekly=True),
    _t("#Travel", "hashtag", 104, "evening", weekly=True),
    _t("#Wanderlust", "hashtag", 76, "evening"),
    _t("#Vacation", "hashtag", 90, "daytime", weekly=True),
    _t("#Beach", "hashtag", 82, "daytime", weekly=True),
    _t("#Sunset", "hashtag", 88, "evening"),
    _t("#Sunrise", "hashtag", 74, "morning"),
    _t("#Nature", "hashtag", 86, "morning"),
    _t("#Photography", "hashtag", 94, "evening"),
    _t("#PhotoOfTheDay", "hashtag", 90, "daytime"),
    _t("#InstaGood", "hashtag", 72, "evening"),
    _t("#Art", "hashtag", 84, "evening"),
    _t("#Artist", "hashtag", 70, "night"),
    _t("#Music", "hashtag", 96, "evening"),
    _t("#NewMusic", "hashtag", 82, "evening", weekly=True),
    _t("#Song", "hashtag", 70, "night"),
    _t("#Concert", "hashtag", 88, "night", weekly=True),
    _t("#Festival", "hashtag", 86, "daytime", weekly=True),
    _t("#Movie", "hashtag", 92, "evening", weekly=True),
    _t("#Film", "hashtag", 78, "evening"),
    _t("#TVShow", "hashtag", 74, "night", weekly=True),
    _t("#Series", "hashtag", 72, "night"),
    _t("#Binge", "hashtag", 68, "night", weekly=True),
    _t("#Streaming", "hashtag", 76, "night"),
    _t("#GamingCommunity", "hashtag", 70, "latenight"),
    _t("#Esports", "hashtag", 74, "latenight"),
    _t("#Streamer", "hashtag", 68, "latenight"),
    _t("#Twitch", "hashtag", 80, "latenight"),
    _t("#Kick", "hashtag", 66, "latenight"),
    _t("#YouTube", "hashtag", 84, "evening"),
    _t("#TikTok", "hashtag", 98, "evening"),
    _t("#Reels", "hashtag", 72, "evening"),
    _t("#Shorts", "hashtag", 68, "evening"),
    _t("#Podcast", "hashtag", 70, "morning"),
    _t("#BookTwitter", "hashtag", 64, "night"),
    _t("#Reading", "hashtag", 66, "latenight"),
    _t("#Study", "hashtag", 70, "night"),
    _t("#Student", "hashtag", 64, "evening"),
    _t("#College", "hashtag", 68, "evening"),
    _t("#Graduation", "hashtag", 80, "daytime", weekly=True),
    _t("#Job", "hashtag", 66, "morning"),
    _t("#Career", "hashtag", 62, "morning"),
    _t("#RemoteWork", "hashtag", 68, "morning"),
    _t("#WorkFromHome", "hashtag", 72, "morning"),
    _t("#Startup", "hashtag", 74, "daytime"),
    _t("#Entrepreneur", "hashtag", 70, "morning"),
    _t("#Business", "hashtag", 76, "morning"),
    _t("#Investing", "hashtag", 82, "morning"),
    _t("#Stocks", "hashtag", 80, "morning"),
    _t("#Money", "hashtag", 78, "daytime"),
    _t("#Finance", "hashtag", 70, "daytime"),
    _t("#Budget", "hashtag", 60, "daytime"),
    _t("#Savings", "hashtag", 58, "daytime"),
    _t("#SideHustle", "hashtag", 64, "night"),
    _t("#Dog", "hashtag", 90, "evening"),
    _t("#Cat", "hashtag", 92, "night"),
    _t("#Pets", "hashtag", 80, "evening"),
    _t("#Puppy", "hashtag", 76, "evening"),
    _t("#Kitten", "hashtag", 74, "night"),
    _t("#Cute", "hashtag", 86, "evening"),
    _t("#Funny", "hashtag", 88, "night"),
    _t("#Meme", "hashtag", 84, "latenight"),
    _t("#Viral", "hashtag", 90, "evening", daily=True),
    _t("#Trending", "hashtag", 82, "evening"),
    _t("#News", "hashtag", 96, "daytime"),
    _t("#Politics", "hashtag", 94, "daytime"),
    _t("#World", "hashtag", 78, "daytime"),
    _t("#USA", "hashtag", 86, "daytime"),
    _t("#UK", "hashtag", 76, "daytime"),
    _t("#Canada", "hashtag", 70, "daytime"),
    _t("#Australia", "hashtag", 72, "daytime"),
    _t("#Europe", "hashtag", 74, "daytime"),
    _t("#Asia", "hashtag", 70, "daytime"),
    _t("#Africa", "hashtag", 62, "daytime"),
    _t("#LatAm", "hashtag", 58, "daytime"),
    _t("#MiddleEast", "hashtag", 60, "daytime"),
    _t("#Climate", "hashtag", 78, "daytime"),
    _t("#Environment", "hashtag", 70, "daytime"),
    _t("#Sustainability", "hashtag", 62, "daytime"),
    _t("#Science", "hashtag", 76, "daytime"),
    _t("#Space", "hashtag", 88, "night"),
    _t("#NASA", "hashtag", 84, "daytime"),
    _t("#Astronomy", "hashtag", 70, "latenight"),
    _t("#Moon", "hashtag", 68, "night"),
    _t("#Mars", "hashtag", 72, "night"),
    _t("#Stars", "hashtag", 64, "latenight"),
    _t("#Galaxy", "hashtag", 60, "latenight"),
    _t("#Tech", "hashtag", 80, "daytime"),
    _t("#Innovation", "hashtag", 66, "daytime"),
    _t("#Future", "hashtag", 64, "daytime"),
    _t("#Robot", "hashtag", 58, "daytime"),
    _t("#Drone", "hashtag", 60, "daytime"),
    _t("#Cybersecurity", "hashtag", 68, "daytime"),
    _t("#Privacy", "hashtag", 62, "daytime"),
    _t("#Data", "hashtag", 60, "daytime"),
    _t("#Coding", "hashtag", 74, "latenight"),
    _t("#Programming", "hashtag", 70, "latenight"),
    _t("#Developer", "hashtag", 66, "latenight"),
    _t("#Python", "hashtag", 68, "latenight"),
    _t("#JavaScript", "hashtag", 64, "latenight"),
    _t("#WebDev", "hashtag", 58, "latenight"),
    _t("#OpenSource", "hashtag", 60, "latenight"),
    _t("#GitHub", "hashtag", 62, "latenight"),
    _t("#BuildInPublic", "hashtag", 56, "daytime"),
    _t("#IndieHacker", "hashtag", 52, "daytime"),
    _t("#Marketing", "hashtag", 60, "daytime"),
    _t("#SEO", "hashtag", 56, "daytime"),
    _t("#Branding", "hashtag", 54, "daytime"),
    _t("#Design", "hashtag", 66, "daytime"),
    _t("#UX", "hashtag", 58, "daytime"),
    _t("#UI", "hashtag", 56, "daytime"),
    _t("#ProductDesign", "hashtag", 50, "daytime"),
    _t("#Architecture", "hashtag", 52, "daytime"),
    _t("#Interior", "hashtag", 54, "evening"),
    _t("#Fashion", "hashtag", 82, "evening"),
    _t("#Style", "hashtag", 74, "evening"),
    _t("#Beauty", "hashtag", 78, "evening"),
    _t("#Makeup", "hashtag", 72, "morning"),
    _t("#Skincare", "hashtag", 68, "night"),
    _t("#Hair", "hashtag", 60, "daytime"),
    _t("#Nails", "hashtag", 58, "evening"),
    _t("#Perfume", "hashtag", 52, "evening"),
    _t("#Jewelry", "hashtag", 54, "evening"),
    _t("#Watch", "hashtag", 56, "daytime"),
    _t("#Sneakers", "hashtag", 66, "evening"),
    _t("#Streetwear", "hashtag", 60, "evening"),
    _t("#Vintage", "hashtag", 56, "daytime"),
    _t("#Thrift", "hashtag", 52, "daytime", weekly=True),
    _t("#DIY", "hashtag", 58, "daytime", weekly=True),
    _t("#HomeDecor", "hashtag", 56, "evening"),
    _t("#Garden", "hashtag", 54, "morning", weekly=True),
    _t("#Plants", "hashtag", 56, "morning"),
    _t("#Flowers", "hashtag", 58, "morning"),
    _t("#Spring", "hashtag", 70, "morning", weekly=True),
    _t("#Summer", "hashtag", 82, "daytime", weekly=True),
    _t("#Fall", "hashtag", 72, "morning", weekly=True),
    _t("#Autumn", "hashtag", 68, "morning", weekly=True),
    _t("#Winter", "hashtag", 74, "morning", weekly=True),
    _t("#Rain", "hashtag", 62, "morning", daily=True),
    _t("#Snow", "hashtag", 66, "morning", daily=True),
    _t("#Sunshine", "hashtag", 60, "morning"),
    _t("#Clouds", "hashtag", 54, "daytime"),
    _t("#Rainbow", "hashtag", 58, "evening", daily=True),
    _t("#Storm", "hashtag", 64, "evening", daily=True),
    _t("#Weather", "hashtag", 70, "morning"),
    _t("#Holiday", "hashtag", 86, "daytime", weekly=True),
    _t("#Celebration", "hashtag", 66, "evening"),
    _t("#Party", "hashtag", 72, "night", weekly=True),
    _t("#Birthday", "hashtag", 80, "evening"),
    _t("#Anniversary", "hashtag", 64, "evening"),
    _t("#Wedding", "hashtag", 76, "daytime", weekly=True),
    _t("#Family", "hashtag", 74, "evening"),
    _t("#Friends", "hashtag", 72, "evening"),
    _t("#Love", "hashtag", 88, "night"),
    _t("#Happy", "hashtag", 78, "evening"),
    _t("#Grateful", "hashtag", 62, "morning"),
    _t("#Blessed", "hashtag", 60, "morning"),
    _t("#Positive", "hashtag", 58, "morning"),
    _t("#Inspiration", "hashtag", 64, "morning"),
    _t("#Quote", "hashtag", 62, "morning"),
    _t("#Wisdom", "hashtag", 54, "morning"),
    _t("#Life", "hashtag", 66, "evening"),
    _t("#Goals", "hashtag", 60, "morning"),
    _t("#Success", "hashtag", 58, "morning"),
    _t("#Hustle", "hashtag", 56, "morning"),
    _t("#Grind", "hashtag", 50, "latenight"),
    _t("#Motivation", "hashtag", 76, "morning"),
    _t("#Mindset", "hashtag", 58, "morning"),
    _t("#Wellness", "hashtag", 56, "morning"),
    _t("#Meditation", "hashtag", 52, "morning"),
    _t("#Mindfulness", "hashtag", 50, "morning"),
    _t("#Therapy", "hashtag", 54, "night"),
    _t("#Anxiety", "hashtag", 58, "night"),
    _t("#Depression", "hashtag", 56, "night"),
    _t("#Support", "hashtag", 52, "night"),
    _t("#Community", "hashtag", 58, "evening"),
    _t("#Together", "hashtag", 50, "evening"),
    _t("#Unity", "hashtag", 48, "evening"),
    _t("#Peace", "hashtag", 60, "evening"),
    _t("#Hope", "hashtag", 56, "morning"),
    _t("#Freedom", "hashtag", 54, "daytime"),
    _t("#Justice", "hashtag", 62, "daytime"),
    _t("#Equality", "hashtag", 56, "daytime"),
    _t("#Rights", "hashtag", 54, "daytime"),
    _t("#Vote", "hashtag", 78, "daytime", daily=True),
    _t("#Democracy", "hashtag", 60, "daytime"),
    _t("#Elections", "hashtag", 74, "daytime", daily=True),
    _t("#Politics", "hashtag", 70, "daytime"),
    _t("#Government", "hashtag", 58, "daytime"),
    _t("#Policy", "hashtag", 52, "daytime"),
    _t("#Law", "hashtag", 54, "daytime"),
    _t("#Court", "hashtag", 56, "daytime", daily=True),
    _t("#Judge", "hashtag", 50, "daytime"),
    _t("#Jury", "hashtag", 46, "daytime"),
    _t("#Verdict", "hashtag", 52, "daytime", daily=True),
    _t("#Sentence", "hashtag", 48, "daytime", daily=True),
    _t("#Prison", "hashtag", 50, "night"),
    _t("#Police", "hashtag", 66, "night", daily=True),
    _t("#Crime", "hashtag", 64, "night", daily=True),
    _t("#Safety", "hashtag", 54, "daytime"),
    _t("#Security", "hashtag", 52, "daytime"),
    _t("#Emergency", "hashtag", 58, None, daily=True),
    _t("#Alert", "hashtag", 62, None, daily=True),
    _t("#Warning", "hashtag", 56, None, daily=True),
    _t("#Evacuation", "hashtag", 54, None, daily=True),
    _t("#Rescue", "hashtag", 52, "daytime", daily=True),
    _t("#Relief", "hashtag", 48, "daytime"),
    _t("#Donation", "hashtag", 46, "evening"),
    _t("#Charity", "hashtag", 48, "evening"),
    _t("#Volunteer", "hashtag", 46, "daytime", weekly=True),
    _t("#Fundraiser", "hashtag", 44, "evening"),
    _t("#GoFundMe", "hashtag", 42, "evening"),
]

# 全世界共通で流れやすい話題（どの地点でも一定割合で出現 → 地域比較が面白くなる）
GLOBAL: list[dict] = [
    _t("Elon Musk", "tech", 190, "night", daily=True),
    _t("OpenAI", "tech", 180, "daytime", daily=True),
    _t("ChatGPT", "tech", 170, "daytime"),
    _t("AI", "tech", 165, "daytime"),
    _t("Grok", "tech", 130, "night", daily=True),
    _t("Gemini", "tech", 128, "daytime", daily=True),
    _t("Tesla", "tech", 150, "night", daily=True),
    _t("SpaceX", "tech", 124, "night", daily=True),
    _t("iPhone", "tech", 158, "evening", daily=True),
    _t("Apple", "tech", 148, "evening", daily=True),
    _t("Google", "tech", 132, "daytime"),
    _t("Microsoft", "tech", 120, "daytime"),
    _t("Nvidia", "tech", 126, "morning", daily=True),
    _t("Nintendo Switch 2", "anime_game", 150, "daytime", daily=True),
    _t("GTA 6", "anime_game", 168, "night", daily=True),
    _t("Fortnite", "anime_game", 140, "night"),
    _t("Minecraft", "anime_game", 138, "evening"),
    _t("Pokémon", "anime_game", 155, "evening"),
    _t("Genshin Impact", "anime_game", 142, "night"),
    _t("原神", "anime_game", 138, "night"),
    _t("One Piece", "anime_game", 160, "night"),
    _t("ONE PIECE", "anime_game", 150, "night"),
    _t("Demon Slayer", "anime_game", 165, "night"),
    _t("鬼滅の刃", "anime_game", 160, "night"),
    _t("Jujutsu Kaisen", "anime_game", 140, "latenight"),
    _t("Studio Ghibli", "anime_game", 130, "evening", daily=True),
    _t("BTS", "entertainment", 170, "evening"),
    _t("BLACKPINK", "entertainment", 150, "evening"),
    _t("NewJeans", "entertainment", 132, "evening", daily=True),
    _t("Stray Kids", "entertainment", 128, "night", daily=True),
    _t("SEVENTEEN", "entertainment", 126, "night", daily=True),
    _t("Taylor Swift", "entertainment", 175, "evening", daily=True),
    _t("Sabrina Carpenter", "entertainment", 138, "evening", daily=True),
    _t("Billie Eilish", "entertainment", 124, "night", daily=True),
    _t("Drake", "entertainment", 130, "latenight", daily=True),
    _t("Bad Bunny", "entertainment", 128, "night", daily=True),
    _t("Kendrick Lamar", "entertainment", 126, "night", daily=True),
    _t("Netflix", "lifestyle", 155, "night"),
    _t("Squid Game", "entertainment", 150, "night", daily=True),
    _t("Stranger Things", "entertainment", 138, "night", daily=True),
    _t("Wednesday", "entertainment", 128, "night", daily=True),
    _t("Marvel", "entertainment", 148, "evening", daily=True),
    _t("Spider-Man", "entertainment", 142, "evening", daily=True),
    _t("Star Wars", "entertainment", 136, "night", daily=True),
    _t("Deadpool", "entertainment", 122, "night", daily=True),
    _t("Oscars", "entertainment", 140, "night", weekly=True),
    _t("Super Bowl", "sports", 175, "night", weekly=True),
    _t("NBA", "sports", 160, "night"),
    _t("LeBron", "sports", 138, "night", daily=True),
    _t("Lakers", "sports", 140, "night", daily=True),
    _t("NFL", "sports", 150, "night", weekly=True),
    _t("Chiefs", "sports", 136, "night", weekly=True),
    _t("MLB", "sports", 148, "night"),
    _t("Dodgers", "sports", 168, "night", daily=True),
    _t("Shohei Ohtani", "sports", 190, "morning", daily=True),
    _t("大谷翔平", "sports", 200, "morning", daily=True),
    _t("Yankees", "sports", 134, "night", daily=True),
    _t("World Series", "sports", 158, "night", weekly=True),
    _t("Premier League", "sports", 162, "night", weekly=True),
    _t("Champions League", "sports", 170, "night", weekly=True),
    _t("Real Madrid", "sports", 164, "night", daily=True),
    _t("Barcelona", "sports", 156, "night", daily=True),
    _t("Arsenal", "sports", 138, "night", weekly=True),
    _t("Liverpool", "sports", 142, "night", weekly=True),
    _t("Manchester City", "sports", 136, "night", weekly=True),
    _t("Messi", "sports", 166, "night", daily=True),
    _t("Cristiano Ronaldo", "sports", 162, "night", daily=True),
    _t("Mbappé", "sports", 140, "night", daily=True),
    _t("Haaland", "sports", 134, "night", daily=True),
    _t("World Cup", "sports", 195, "night", daily=True),
    _t("W杯", "sports", 180, "night", daily=True),
    _t("F1", "sports", 140, "night", weekly=True),
    _t("Verstappen", "sports", 122, "night", weekly=True),
    _t("UFC", "sports", 128, "latenight", weekly=True),
    _t("Djokovic", "sports", 120, "night", daily=True),
    _t("Alcaraz", "sports", 124, "night", daily=True),
    _t("Sinner", "sports", 122, "night", daily=True),
    _t("Wimbledon", "sports", 130, "night", weekly=True),
    _t("US Open", "sports", 126, "night", weekly=True),
    _t("Olympics", "sports", 150, "daytime"),
    _t("オリンピック", "sports", 140, "daytime"),
    _t("Donald Trump", "news", 220, "daytime", daily=True),
    _t("Trump", "news", 210, "daytime", daily=True),
    _t("トランプ大統領", "news", 170, "night", daily=True),
    _t("White House", "news", 160, "daytime", daily=True),
    _t("Supreme Court", "news", 140, "daytime", daily=True),
    _t("Election", "news", 180, "daytime", daily=True),
    _t("選挙", "news", 175, "daytime", daily=True),
    _t("Government Shutdown", "news", 150, "daytime", daily=True),
    _t("Tariffs", "finance", 158, "morning", daily=True),
    _t("関税", "finance", 120, "morning", daily=True),
    _t("Federal Reserve", "finance", 146, "daytime", daily=True),
    _t("FRB", "finance", 120, "morning"),
    _t("Interest Rates", "finance", 132, "daytime"),
    _t("Inflation", "finance", 138, "daytime"),
    _t("Recession", "finance", 130, "daytime", daily=True),
    _t("Stock Market", "finance", 164, "morning"),
    _t("日経平均", "finance", 160, "morning"),
    _t("S&P 500", "finance", 142, "morning"),
    _t("Nasdaq", "finance", 134, "morning"),
    _t("Market Crash", "finance", 148, "morning", daily=True),
    _t("Bitcoin", "finance", 188, "night", daily=True),
    _t("ビットコイン", "finance", 145, "night", daily=True),
    _t("Crypto", "finance", 162, "night"),
    _t("Ethereum", "finance", 128, "night", daily=True),
    _t("Solana", "finance", 112, "night", daily=True),
    _t("XRP", "finance", 116, "night", daily=True),
    _t("Dogecoin", "finance", 118, "night", daily=True),
    _t("Gold", "finance", 114, "morning", daily=True),
    _t("Oil", "finance", 120, "morning", daily=True),
    _t("Earthquake", "news", 180, None, daily=True),
    _t("地震", "news", 210, None, daily=True),
    _t("Tsunami", "news", 140, None, daily=True),
    _t("Hurricane", "news", 175, "daytime", daily=True),
    _t("台風", "news", 190, "daytime", daily=True),
    _t("Wildfire", "news", 155, "daytime", daily=True),
    _t("Flood", "news", 132, "morning", daily=True),
    _t("Heat Wave", "news", 130, "daytime", daily=True),
    _t("猛暑日", "news", 145, "daytime", daily=True),
    _t("Storm", "news", 134, "evening", daily=True),
    _t("Crash", "news", 126, "daytime", daily=True),
    _t("Shooting", "news", 152, "evening", daily=True),
    _t("Arrest", "news", 138, "evening", daily=True),
    _t("逮捕", "news", 150, "evening", daily=True),
    _t("Trial", "news", 130, "daytime", daily=True),
    _t("Ukraine", "news", 186, "daytime", daily=True),
    _t("ウクライナ", "news", 155, "daytime", daily=True),
    _t("Russia", "news", 178, "daytime", daily=True),
    _t("ロシア", "news", 148, "daytime", daily=True),
    _t("Putin", "news", 150, "daytime", daily=True),
    _t("Zelensky", "news", 142, "daytime", daily=True),
    _t("Ceasefire", "news", 138, "daytime", daily=True),
    _t("停戦", "news", 125, "daytime", daily=True),
    _t("NATO", "news", 126, "daytime"),
    _t("Israel", "news", 172, "daytime", daily=True),
    _t("イスラエル", "news", 145, "daytime", daily=True),
    _t("Gaza", "news", 168, "daytime", daily=True),
    _t("ガザ", "news", 140, "daytime", daily=True),
    _t("Iran", "news", 150, "daytime", daily=True),
    _t("China", "news", 160, "daytime", daily=True),
    _t("中国", "news", 118, "daytime", daily=True),
    _t("North Korea", "news", 130, "daytime", daily=True),
    _t("北朝鮮", "news", 124, "daytime", daily=True),
    _t("Immigration", "news", 140, "daytime", daily=True),
    _t("Protest", "news", 132, "evening", daily=True),
    _t("Climate Change", "news", 122, "daytime", daily=True),
    _t("気候変動", "news", 100, "daytime", daily=True),
    _t("Breaking News", "news", 145, "daytime", daily=True),
    _t("Viral", "lifestyle", 126, "evening", daily=True),
    _t("Meme", "lifestyle", 120, "night", daily=True),
    _t("Black Friday", "lifestyle", 155, "night"),
    _t("Prime Day", "lifestyle", 132, "daytime"),
    _t("Amazon", "lifestyle", 128, "evening"),
    _t("Starbucks", "lifestyle", 140, "morning", daily=True),
    _t("スタバ", "lifestyle", 130, "morning", daily=True),
    _t("McDonald's", "lifestyle", 134, "daytime", daily=True),
    _t("マクドナルド", "lifestyle", 126, "daytime", daily=True),
    _t("Costco", "lifestyle", 104, "daytime", weekly=True),
    _t("コストコ", "lifestyle", 104, "daytime", weekly=True),
    _t("Disney", "lifestyle", 152, "daytime", weekly=True),
    _t("ディズニー", "lifestyle", 148, "daytime", weekly=True),
    _t("TikTok", "lifestyle", 165, "evening"),
    _t("YouTube", "lifestyle", 158, "evening"),
    _t("Instagram", "lifestyle", 142, "evening"),
    _t("Halloween", "lifestyle", 172, "evening"),
    _t("ハロウィン", "lifestyle", 160, "evening"),
    _t("Christmas", "lifestyle", 185, "evening"),
    _t("クリスマス", "lifestyle", 175, "evening"),
    _t("Thanksgiving", "lifestyle", 175, "daytime"),
    _t("New Year", "lifestyle", 165, "night"),
    _t("お正月", "lifestyle", 170, "morning"),
    _t("World Cup Qualifier", "sports", 120, "night", weekly=True),
    _t("#AI", "hashtag", 130, "daytime"),
    _t("#ChatGPT", "hashtag", 118, "daytime"),
    _t("#Bitcoin", "hashtag", 122, "night"),
    _t("#Crypto", "hashtag", 108, "night"),
    _t("#BreakingNews", "hashtag", 132, "daytime", daily=True),
    _t("#Trump", "hashtag", 140, "daytime", daily=True),
    _t("#Election", "hashtag", 126, "daytime", daily=True),
    _t("#TaylorSwift", "hashtag", 148, "evening", daily=True),
    _t("#BTS", "hashtag", 138, "evening"),
    _t("#BLACKPINK", "hashtag", 128, "evening"),
    _t("#Marvel", "hashtag", 122, "evening", daily=True),
    _t("#StarWars", "hashtag", 118, "night", daily=True),
    _t("#Netflix", "hashtag", 114, "night"),
    _t("#Anime", "hashtag", 126, "night"),
    _t("#アニメ", "hashtag", 96, "night"),
    _t("#OnePiece", "hashtag", 118, "night"),
    _t("#DemonSlayer", "hashtag", 112, "night"),
    _t("#鬼滅の刃", "hashtag", 140, "night"),
    _t("#GenshinImpact", "hashtag", 108, "night"),
    _t("#原神", "hashtag", 120, "night"),
    _t("#GTA6", "hashtag", 132, "night", daily=True),
    _t("#Fortnite", "hashtag", 110, "night"),
    _t("#NintendoSwitch2", "hashtag", 114, "daytime", daily=True),
    _t("#iPhone", "hashtag", 116, "evening", daily=True),
    _t("#Tesla", "hashtag", 120, "night", daily=True),
    _t("#SpaceX", "hashtag", 106, "night", daily=True),
    _t("#ElonMusk", "hashtag", 124, "night", daily=True),
    _t("#イーロンマスク", "hashtag", 100, "night", daily=True),
    _t("#UCL", "hashtag", 124, "night", weekly=True),
    _t("#PremierLeague", "hashtag", 110, "night", weekly=True),
    _t("#NBA", "hashtag", 118, "night"),
    _t("#MLB", "hashtag", 116, "night"),
    _t("#F1", "hashtag", 110, "night", weekly=True),
    _t("#W杯", "hashtag", 135, "night", daily=True),
    _t("#WorldCup", "hashtag", 130, "night", daily=True),
    _t("#地震", "hashtag", 180, None, daily=True),
    _t("#台風", "hashtag", 150, "daytime", daily=True),
    _t("#Earthquake", "hashtag", 120, None, daily=True),
    _t("#大谷さん", "hashtag", 130, "morning", daily=True),
    _t("#Ohtani", "hashtag", 118, "morning", daily=True),
    _t("#GoodMorning", "hashtag", 118, "morning"),
    _t("#GoodNight", "hashtag", 108, "latenight"),
    _t("#おはよう", "hashtag", 122, "morning"),
    _t("#おやすみ", "hashtag", 118, "latenight"),
    _t("#Viral", "hashtag", 92, "evening", daily=True),
    _t("#Trending", "hashtag", 88, "evening"),
    _t("#News", "hashtag", 96, "daytime"),
    _t("#Politics", "hashtag", 94, "daytime"),
    _t("#Climate", "hashtag", 78, "daytime"),
    _t("#Space", "hashtag", 88, "night"),
    _t("#NASA", "hashtag", 84, "daytime"),
    _t("#Tech", "hashtag", 80, "daytime"),
    _t("#Music", "hashtag", 96, "evening"),
    _t("#Movie", "hashtag", 92, "evening", weekly=True),
    _t("#Gaming", "hashtag", 120, "night"),
    _t("#Kpop", "hashtag", 116, "night"),
    _t("#Travel", "hashtag", 104, "evening", weekly=True),
    _t("#Foodie", "hashtag", 92, "evening"),
    _t("#Fashion", "hashtag", 82, "evening"),
    _t("#Photography", "hashtag", 94, "evening"),
    _t("#Love", "hashtag", 88, "night"),
    _t("#Motivation", "hashtag", 76, "morning"),
]

_POOLS = {"ja": _JA, "en": _EN, "global": _EN}


def _dedupe(pool: list[dict]) -> list[dict]:
    seen: set[str] = set()
    out: list[dict] = []
    for item in pool:
        if item["name"] in seen:
            continue
        seen.add(item["name"])
        out.append(item)
    return out


@lru_cache(maxsize=8)
def build_pool(locale: str) -> tuple[dict, ...]:
    """ロケール別の話題プール（重複除去済み・キャッシュあり）。"""
    return tuple(_dedupe(_POOLS.get(locale, _EN)))


@lru_cache(maxsize=1)
def global_pool() -> tuple[dict, ...]:
    """全世界共通プールの重複除去版。"""
    return tuple(_dedupe(GLOBAL))


GLOBAL_DEDUPED = global_pool()
